"""One example of each record. Every value is made up, and every id says so.

They are shaped as real ones will be and describe the synthetic city. The
README prints them, and a test holds the README to what is here.
"""

import hashlib

from burro_pipeline.evidence.claim import (
    Claim,
    ClaimKind,
    Derived,
    FoundBy,
    Review,
    Reviewer,
    ReviewStatus,
    claim_id_of,
    text_sha256,
)
from burro_pipeline.evidence.method import Kind, Method
from burro_pipeline.evidence.receipt import Geography, Period, made_up_receipt
from burro_pipeline.evidence.record import MADE_UP_SOURCE
from burro_pipeline.evidence.row import EvidenceRow, Flag, State
from burro_pipeline.registry.model import Use

RETRIEVED_AT = "2026-09-23T09:12:31Z"
RELEASE_ID = "syn-2026-09-23-01"
AREA_ID = "syn-n0001"

# The receipt of a file of parks, and of the file of homes that a walk is weighted by.
RECEIPT = made_up_receipt(
    "made-up-parks.gpkg", Use.SCORING, Geography.POLYGON, Period(as_at="2025-04"), RETRIEVED_AT
)
HOMES = made_up_receipt(
    "made-up-homes.csv", Use.SCORING, Geography.OA21, Period(as_at="2021-03-21"), RETRIEVED_AT
)

METHOD = Method(
    derivation_id="walk_to_nearest@1",
    sentence="The walk from homes to the nearest park of 2 hectares or more, taken as the "
    "median by homes and rounded to 10 metres.",
    kind=Kind.MEASURED,
    parameters={"hectares": 2, "rounded_to_metres": 10},
    code="burro_pipeline.derive.walk",
)

ROW = EvidenceRow(
    fact_id=f"{AREA_ID}/feature/park_proximity",
    derivation_id=METHOD.derivation_id,
    inputs=tuple(sorted((RECEIPT.file_id, HOMES.file_id))),
    data_period=Period(start="2021-03-21", end="2025-04-30"),
    retrieved_on="2026-09-23",
    units_used=10,
    units_expected=11,
    weight_covered=0.97,
    state=State.PARTIAL,
    flags=(Flag.UNIT_SPLIT,),
    value=290.0,
)

# A made-up page of a made-up encyclopaedia, and the one sentence a claim quotes from it.
PAGE_TEXT = "Alderwick is a district of Quillhaven. The station at Alderwick opened in 1907.\n"
QUOTE = "The station at Alderwick opened in 1907."
PAGE = made_up_receipt(
    "made-up-page.html", Use.PROFILE_TEXT, Geography.NONE, Period(as_at="2026-08-30"), RETRIEVED_AT
)

CLAIM = Claim(
    claim_id=claim_id_of(AREA_ID, MADE_UP_SOURCE, 4021, QUOTE),
    area_id=AREA_ID,
    kind=ClaimKind.HISTORY,
    quote=QUOTE,
    source_id=MADE_UP_SOURCE,
    page=PAGE.file_id,
    title="Alderwick",
    url="",
    page_id=4021,
    revision_id=88213,
    source_dated="2026-08-30T17:40:02Z",
    retrieved_at=RETRIEVED_AT,
    raw_sha256=PAGE.sha256,
    text_sha256=text_sha256(PAGE_TEXT),
    start=PAGE_TEXT.index(QUOTE),
    end=PAGE_TEXT.index(QUOTE) + len(QUOTE),
    section="History",
    derived=Derived(
        method=FoundBy.MODEL_SELECT,
        reader_version="1",
        checks_version="1",
        prompt_version=hashlib.sha256(b"a made-up prompt").hexdigest()[:12],
        provider="made-up-provider",
        model="made-up-model",
    ),
    has_reference=True,
    review=Review(
        status=ReviewStatus.ACCEPTED, reviewed_on="2026-09-23", reviewer=Reviewer.FOUNDER
    ),
    first_release=RELEASE_ID,
    licence="None. Made up for testing",
    attribution="Synthetic data generated by Burro for testing. It describes no real place.",
)
