"""The data release: its records, the protocol ranking reads it through, and the one parser.

A release is data and nothing else. `parse_release` and `open_release` do all
the checking, so the pipeline that writes a release and the API that loads one
cannot come to disagree about what a valid release is. Neither opens a file:
the caller reads the bytes and hands them over.

A release that is not made up is served only with what it was built with: its
evidence, its lock, and the hashes of the build. `open_served` holds the three
to each other. It reads none of the evidence. It is what keeps a release that
was changed after it was built, or that has no evidence at all, from being
served.
"""

import hashlib
import json
from collections.abc import Callable, Hashable, Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Annotated, Any, Literal, Protocol, Self, cast

from pydantic import Field, StrictBool, ValidationError, model_validator

from burro_core._record import Record
from burro_core.catalogue import (
    BANDS,
    CATALOGUE_VERSION,
    FEATURES,
    RANKED_AS,
    TAG_MIN_COVERAGE_HUNDREDTHS,
    TAGS,
    Tag,
    band_of,
    percentile_of,
    tag_raw,
    tags_of,
)
from burro_core.ids import (
    DATE_OR_MONTH_PATTERN,
    DATE_PATTERN,
    MONTH_PATTERN,
    SLUG_PATTERN,
    SYNTHETIC_PREFIX,
    SYNTHETIC_SOURCE_ID,
    TIMESTAMP_PATTERN,
    AreaId,
    City,
    Confidence,
    Describes,
    DestinationId,
    Dimension,
    Family,
    FeatureId,
    FeatureKind,
    GeometryType,
    GrittyVariant,
    Method,
    Mode,
    NameState,
    NativeResolution,
    Part,
    PlaceId,
    PlaceKind,
    Polarity,
    PtBasis,
    ReleaseId,
    Segment,
    SourceId,
    StationId,
    TagId,
    Tenure,
    TravelStatus,
    segments_for,
)

SCHEMA_VERSION = 2
SYNTHETIC_ATTRIBUTION = "Synthetic data generated by Burro for testing. It describes no real place."

# Below this share of an area, the source did not cover enough of it to give a value.
FEATURE_MIN_COVERAGE = 0.5
# Beyond the nearest, an area lists only the stations within this walk.
NEARBY_STATION_MINUTES = 10
# The cell of a travel matrix that says "no journey within the cutoff".
BEYOND_CUTOFF_CELL = -1
# The unit of a share of the whole. A figure of any other unit is a count, a level, a
# distance or a rate, and is never below nought.
PERCENT = "%"
# How far a point of an area's outline, or the point inside a neighbour, may lie from the
# point inside the area, in degrees either way. It is some tens of kilometres, which is
# wider than any area: a point further off was drawn in the wrong place.
REACH = 0.5
# The fewest sales a median may rest on, where a row says how many it rests on. With fewer
# there is no figure. It is the least the contract calls an observation of `medium`
# confidence, and `MANY_SALES` is the least it calls `high` (section 2.5).
FEWEST_SALES = 10
MANY_SALES = 50

MANIFEST = "manifest.json"
NEIGHBOURHOODS = "neighbourhoods.json"
GEOMETRY = "geometry.json"
CATALOGUE = "catalogue.json"
FEATURES_FILE = "features.json"
TAGS_FILE = "tags.json"
COST = "cost.json"
DESTINATIONS = "destinations.json"
TRAVEL = "travel.json"
STATIONS = "stations.json"
PLACES = "places.json"

# What stands beside a release that is not made up, in a folder named for the release with
# `BUILD_FOLDER` after it: the hashes of the build, its evidence and its lock.
BUILD_FOLDER = "-build"
HASHES = "hashes.json"
EVIDENCE = "evidence.json"
LOCK = "lock.json"

DATA_FILES = (
    NEIGHBOURHOODS,
    GEOMETRY,
    CATALOGUE,
    FEATURES_FILE,
    TAGS_FILE,
    COST,
    DESTINATIONS,
    TRAVEL,
    STATIONS,
    PLACES,
)


class ReleaseError(Exception):
    """A release broke a rule. Names the file, the row and the rule, and never a value."""

    def __init__(self, file: str, rule: str, row: str = "") -> None:
        self.file = file
        self.rule = rule
        self.row = row
        super().__init__(f"{file}: {row}: {rule}" if row else f"{file}: {rule}")


Share = Annotated[float, Field(ge=0, le=1, allow_inf_nan=False)]
Percentile = Annotated[float, Field(ge=0, le=100, allow_inf_nan=False)]
Band = Annotated[int, Field(ge=1, le=BANDS)]
Point = tuple[
    Annotated[float, Field(ge=-180, le=180, allow_inf_nan=False)],
    Annotated[float, Field(ge=-90, le=90, allow_inf_nan=False)],
]
Text = Annotated[str, Field(min_length=1)]
SourceIds = Annotated[tuple[SourceId, ...], Field(min_length=1)]
# The sources of a part that may hold nothing. `sources_are_stated` says when it may be empty.
SourceIdsIfAny = tuple[SourceId, ...]
DateOrMonthIfAny = Annotated[str, Field(pattern=DATE_OR_MONTH_PATTERN)] | None
Pounds = Annotated[int, Field(ge=0)]
Cell = Annotated[int, Field(ge=BEYOND_CUTOFF_CELL)] | None
Matrix = tuple[tuple[Cell, ...], ...]


class Source(Record):
    source_id: SourceId
    name: Text
    publisher: Text
    licence: Text
    attribution: Text
    url: str
    retrieved_on: str = Field(pattern=DATE_PATTERN)
    # True where the publisher asks that its attribution stands wherever a figure made
    # from its data is shown. Every fact that cites the source then carries it.
    credit_beside_figures: StrictBool = False


class FileEntry(Record):
    name: Text
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    bytes: int = Field(ge=0)


class Counts(Record):
    neighbourhoods: int = Field(ge=0)
    rankable: int = Field(ge=0)
    destinations: int = Field(ge=0)
    places: int = Field(ge=0)
    stations: int = Field(ge=0)


class Manifest(Record):
    release_id: ReleaseId
    schema_version: int
    # An input to the builder, never read from the clock, so a rebuild is byte-identical.
    built_at: str = Field(pattern=TIMESTAMP_PATTERN)
    catalogue_version: int
    # Whether this release carries Gritty, the one vibe that counts recorded crime.
    gritty_variant: GrittyVariant
    synthetic: StrictBool
    # True for a release that is not finished: it is shown to the people who build it and to
    # nobody else. It travels with every response, as `synthetic` does.
    preview: StrictBool
    city: City
    seed: int | None
    sources: tuple[Source, ...]
    files: tuple[FileEntry, ...]
    counts: Counts


class Hashes(Record):
    """The hashes of one build: of the manifest of its release, of its evidence and of its lock.

    The manifest holds the hash of every file of the release, so the three
    together fix every byte that was built. To approve a release is to commit
    this record with its lock.
    """

    release_id: ReleaseId
    manifest_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    evidence_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    lock_sha256: str = Field(pattern=r"^[0-9a-f]{64}$")


class Named(Record):
    """What is known of the name an area bears, where it is not its publisher's label.

    An area is drawn as its publisher draws it, and its publisher labels it
    with a borough and a number. Where the area bears the name of a
    neighbourhood, this says what the label was, who wrote the name, and
    whether a person has checked it. A name is a draft until one has.
    """

    # The label of the area as its publisher gives it. It is shown beside the name.
    label: Text
    # Every source whose own record writes the name, letter for letter.
    source_ids: SourceIds
    state: NameState


class Neighbourhood(Record):
    area_id: AreaId
    slug: str = Field(pattern=SLUG_PATTERN)
    name: Text
    borough: Text
    aliases: tuple[Text, ...]
    centroid: Point
    # The pipeline decides; core only reads.
    rankable: StrictBool
    neighbours: tuple[AreaId, ...]
    # None where the area bears no name but its publisher's label.
    named: Named | None = None
    # Where the homes of the area are taken to stand: the middle of the centres of
    # population of its small census areas. A journey is estimated from it where the
    # release holds no journey time. `None` where a release does not say, and nothing is
    # then estimated: the point inside the area is never put in its place.
    homes_at: Point | None = None


class Metric(Record):
    """A feature this release carries. Core decides what it is; the release says where from."""

    feature_id: FeatureId
    label: str
    short_label: str
    dimension: Dimension
    unit: str
    polarity: Polarity
    kind: FeatureKind
    describes: Describes
    family: Family | None
    method: Method
    in_likeness: StrictBool
    native_resolution: NativeResolution
    source_ids: SourceIds
    vintage: Text
    # False switches the feature off for ranking in this release. Its values are still shown.
    rankable: StrictBool
    definition: Text


class FeatureValue(Record):
    area_id: AreaId
    feature_id: FeatureId
    value: Annotated[float, Field(allow_inf_nan=False)] | None
    percentile: Percentile | None
    coverage: Share


class TagValue(Record):
    """Where one area sits on one vibe. `score` is for ranking and is never printed.

    `band` is what is shown: one of five, counted from the low end. The
    spread is the bands the middle half of the area's homes span, so a mixed
    area is drawn as a range and never as a point in the middle.
    """

    area_id: AreaId
    tag_id: TagId
    raw: Share | None
    score: Percentile | None
    coverage: Share
    band: Band | None
    spread_low: Band | None
    spread_high: Band | None


class CostEstimate(Record):
    """What a home of one kind costs in one area: a range, or one number where no range is known.

    A row holds both quartiles or neither. A row with neither is a median of
    what was paid for the homes that were sold, and is one of two things. A
    publisher's own median is of the twelve months that end with `as_of`, and
    what it rests on is `unstated`: the publisher gives no count of the sales.
    A median worked out from the sales themselves says how many it rests on,
    in `sales`, and the first month they were made in, in `since`. Nothing
    stands in for the range of either.
    """

    area_id: AreaId
    tenure: Tenure
    segment: Segment
    lower_quartile: Pounds | None
    median: Pounds
    upper_quartile: Pounds | None
    confidence: Confidence
    as_of: str = Field(pattern=MONTH_PATTERN)
    # The first month of the sales a median rests on, where the row says how many they are.
    since: Annotated[str, Field(pattern=MONTH_PATTERN)] | None = None
    # How many sales the median rests on. `None` where no source says.
    sales: Annotated[int, Field(ge=1)] | None = None
    source_ids: SourceIds

    @property
    def ranged(self) -> bool:
        """Whether the row holds a range: both of its quartiles."""
        return self.lower_quartile is not None and self.upper_quartile is not None

    @property
    def counted(self) -> bool:
        """Whether the row says how many sales its median rests on."""
        return self.sales is not None


class Destination(Record):
    destination_id: DestinationId
    centroid: Point


class Travel(Record):
    """One journey time. A time that is not known is `None`, and never zero."""

    status: TravelStatus
    minutes: int | None

    @model_validator(mode="after")
    def _minutes_only_when_ok(self) -> Self:
        if (self.status is TravelStatus.OK) != (self.minutes is not None):
            raise ValueError("minutes is set exactly when status is ok")
        if self.status is TravelStatus.ESTIMATED:
            # An estimate is worked out for a search. No release holds one.
            raise ValueError("a release holds no estimate")
        return self


MISSING_TRAVEL = Travel(status=TravelStatus.MISSING, minutes=None)
BEYOND_CUTOFF_TRAVEL = Travel(status=TravelStatus.BEYOND_CUTOFF, minutes=None)


class StationAccess(Record):
    area_id: AreaId
    station_id: StationId
    name: Text
    walk_minutes: int = Field(ge=0)
    lines: Annotated[tuple[Text, ...], Field(min_length=1)]
    step_free: StrictBool
    nearest: StrictBool


class Place(Record):
    place_id: PlaceId
    name: Text
    aliases: tuple[Text, ...]
    kind: PlaceKind
    destination_id: DestinationId
    # A station or district standing in for this place in a shared link.
    coarse_place_id: PlaceId
    centroid: Point
    source_id: SourceId


class Origin(Record):
    """Where one whole file came from, and when.

    The journeys and the stations of a preview may hold nothing, and then state
    no source and no date: there is nothing to cite. `sources_are_stated` says
    when. No fact is ever made from an origin that states none.
    """

    source_ids: SourceIdsIfAny
    as_of: DateOrMonthIfAny

    @property
    def stated(self) -> bool:
        return bool(self.source_ids) and self.as_of is not None


Ring = Annotated[tuple[Point, ...], Field(min_length=4)]
PolygonRings = Annotated[tuple[Ring, ...], Field(min_length=1)]


class Geometry(Record):
    """A GeoJSON geometry object: a polygon or a multipolygon, in WGS84."""

    type: GeometryType
    coordinates: PolygonRings | Annotated[tuple[PolygonRings, ...], Field(min_length=1)]

    @model_validator(mode="after")
    def _coordinates_suit_the_type(self) -> Self:
        # A polygon's first ring holds points; a multipolygon's first member holds rings.
        nested = isinstance(self.coordinates[0][0][0], tuple)
        if nested != (self.type is GeometryType.MULTI_POLYGON):
            raise ValueError("coordinates do not suit the geometry type")
        return self


class AreaGeometry(Record):
    area_id: AreaId
    geometry: Geometry


class Cutoffs(Record):
    """The longest journey the release routed, by mode. Anything longer is `beyond_cutoff`."""

    # No shorter than the shortest cap a commute may have, so every mode can be asked for.
    pt: int = Field(ge=10, le=1440)
    cycle: int = Field(ge=10, le=1440)
    walk: int = Field(ge=10, le=1440)

    def of(self, mode: Mode) -> int:
        return {Mode.PT: self.pt, Mode.CYCLE: self.cycle, Mode.WALK: self.walk}[mode]


class TravelTable(Record):
    """`travel.json` as it is written: four matrices, rows by area and columns by destination.

    A cell is minutes, `-1` for no journey within the cutoff, or `None` for not
    computed. The two spellings exist only here; `Release.travel()` returns a
    `Travel` and nothing outside this module sees a `-1`.
    """

    # Both are empty only in a preview that holds no journey: `sources_are_stated`.
    source_ids: SourceIdsIfAny
    as_of: DateOrMonthIfAny
    area_ids: tuple[AreaId, ...]
    destination_ids: tuple[DestinationId, ...]
    cutoff_minutes: Cutoffs
    pt_typical: Matrix
    pt_just_missed: Matrix
    cycle: Matrix
    walk: Matrix

    def matrix(self, mode: Mode, basis: PtBasis) -> Matrix:
        if mode is Mode.CYCLE:
            return self.cycle
        if mode is Mode.WALK:
            return self.walk
        return self.pt_typical if basis is PtBasis.TYPICAL else self.pt_just_missed


class Release(Protocol):
    """What ranking, facts and the interpreters read a release through.

    The three tuples are ordered by id, and `stations` nearest first. `vibes`
    holds the vibes this release carries, in the order of the shelf. `None`
    means the id is unknown to this release, or for `cost` that there is no
    estimate. `travel` never returns `None`: for a time that is not in the
    release, and for an id it does not know, it answers `missing`.

    `placed` and `costed` say what the release can answer at all. A vibe is
    placed where some area has a band for it, and a kind of home is costed
    where some area has an estimate for it. A wish for what is neither is
    turned away as `not_in_release` and never ranked on: every area would
    lack it, and none would be left to rank.
    """

    @property
    def manifest(self) -> Manifest: ...
    @property
    def neighbourhoods(self) -> tuple[Neighbourhood, ...]: ...
    @property
    def metrics(self) -> tuple[Metric, ...]: ...
    @property
    def places(self) -> tuple[Place, ...]: ...
    @property
    def vibes(self) -> tuple[Tag, ...]: ...
    def neighbourhood(self, area_id: str) -> Neighbourhood | None: ...
    def geometry(self, area_id: str) -> Geometry | None: ...
    def feature(self, area_id: str, feature_id: FeatureId) -> FeatureValue | None: ...
    def tag(self, area_id: str, tag_id: TagId) -> TagValue | None: ...
    def cost(self, area_id: str, tenure: Tenure, segment: Segment) -> CostEstimate | None: ...
    def place(self, place_id: str) -> Place | None: ...
    def travel(self, area_id: str, destination_id: str, mode: Mode, basis: PtBasis) -> Travel: ...
    def stations(self, area_id: str) -> tuple[StationAccess, ...]: ...
    def origin(self, part: Part) -> Origin: ...
    def cutoff(self, mode: Mode) -> int: ...
    def placed(self, tag_id: TagId) -> bool: ...
    def costed(self, tenure: Tenure, segment: Segment) -> bool: ...


class WaitsOn(Record):
    """A part of a recipe that a release carries no measure for. It is named, never filled in."""

    feature_id: FeatureId
    # The name of the measure, as the catalogue gives it.
    label: str
    hundredths: int = Field(ge=1, le=100)


class RecipeHeld(Record):
    """How much of one vibe's recipe a release carries, and what the vibe waits on.

    It is of the release and of no area. An area may have a figure for fewer
    parts than the release carries, and its own fact says so.
    """

    tag_id: TagId
    # The hundredths of the recipe that the release carries a measure for.
    held: int = Field(ge=0, le=100)
    # The least an area must have a figure for, in hundredths, to be given a band.
    needed: int = Field(ge=1, le=100)
    # Whether any area has a band. Where none has, a wish for the vibe is
    # turned away as `not_in_release`.
    placed: StrictBool
    # The parts the release carries no measure for, in the order of the recipe.
    waits_on: tuple[WaitsOn, ...]


def recipes_held(release: Release) -> tuple[RecipeHeld, ...]:
    """What the release holds of each vibe it carries, in the order of the shelf."""
    carried = {metric.feature_id for metric in release.metrics}
    return tuple(
        RecipeHeld(
            tag_id=vibe.tag_id,
            held=sum(term.hundredths for term in vibe.terms if term.feature_id in carried),
            needed=TAG_MIN_COVERAGE_HUNDREDTHS,
            placed=release.placed(vibe.tag_id),
            waits_on=tuple(
                WaitsOn(
                    feature_id=term.feature_id,
                    label=FEATURES[term.feature_id].label,
                    hundredths=term.hundredths,
                )
                for term in vibe.terms
                if term.feature_id not in carried
            ),
        )
        for vibe in release.vibes
    )


def _station_order(row: StationAccess) -> tuple[str, bool, int, str]:
    return (row.area_id, not row.nearest, row.walk_minutes, row.station_id)


def _shelf_order(tag: Tag) -> tuple[int, str]:
    return (tag.shelf_order or 0, tag.tag_id)


@dataclass(frozen=True)
class InMemoryRelease:
    """A whole release held as records. The one implementation of `Release` in this build.

    Every tuple is put in one order on construction, so two releases built from
    the same rows in a different order are equal and are written the same. The
    constructor checks nothing: `parse_release` does, and a release built by
    hand in a test is as good as its author.
    """

    manifest: Manifest
    neighbourhoods: tuple[Neighbourhood, ...]
    neighbourhoods_origin: Origin
    travel_table: TravelTable
    stations_origin: Origin
    metrics: tuple[Metric, ...] = ()
    features: tuple[FeatureValue, ...] = ()
    tags: tuple[TagValue, ...] = ()
    costs: tuple[CostEstimate, ...] = ()
    destinations: tuple[Destination, ...] = ()
    places: tuple[Place, ...] = ()
    station_rows: tuple[StationAccess, ...] = ()
    geometries: tuple[AreaGeometry, ...] = ()
    vibes: tuple[Tag, ...] = ()

    _areas: Mapping[str, Neighbourhood] = field(init=False, repr=False, compare=False)
    _geometries: Mapping[str, Geometry] = field(init=False, repr=False, compare=False)
    _features: Mapping[tuple[str, FeatureId], FeatureValue] = field(
        init=False, repr=False, compare=False
    )
    _tags: Mapping[tuple[str, TagId], TagValue] = field(init=False, repr=False, compare=False)
    _costs: Mapping[tuple[str, Tenure, Segment], CostEstimate] = field(
        init=False, repr=False, compare=False
    )
    _places: Mapping[str, Place] = field(init=False, repr=False, compare=False)
    _stations: Mapping[str, tuple[StationAccess, ...]] = field(
        init=False, repr=False, compare=False
    )
    _rows: Mapping[str, int] = field(init=False, repr=False, compare=False)
    _columns: Mapping[str, int] = field(init=False, repr=False, compare=False)
    _placed: frozenset[TagId] = field(init=False, repr=False, compare=False)
    _costed: frozenset[tuple[Tenure, Segment]] = field(init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        put = object.__setattr__
        put(self, "neighbourhoods", tuple(sorted(self.neighbourhoods, key=lambda n: n.area_id)))
        put(self, "metrics", tuple(sorted(self.metrics, key=lambda m: m.feature_id)))
        put(self, "features", tuple(sorted(self.features, key=lambda f: (f.area_id, f.feature_id))))
        put(self, "tags", tuple(sorted(self.tags, key=lambda t: (t.area_id, t.tag_id))))
        put(
            self,
            "costs",
            tuple(sorted(self.costs, key=lambda c: (c.area_id, c.tenure, c.segment))),
        )
        put(self, "destinations", tuple(sorted(self.destinations, key=lambda d: d.destination_id)))
        put(self, "places", tuple(sorted(self.places, key=lambda p: p.place_id)))
        put(self, "station_rows", tuple(sorted(self.station_rows, key=_station_order)))
        put(self, "geometries", tuple(sorted(self.geometries, key=lambda g: g.area_id)))
        put(self, "vibes", tuple(sorted(self.vibes, key=_shelf_order)))

        put(self, "_areas", {n.area_id: n for n in self.neighbourhoods})
        put(self, "_geometries", {g.area_id: g.geometry for g in self.geometries})
        put(self, "_features", {(f.area_id, f.feature_id): f for f in self.features})
        put(self, "_tags", {(t.area_id, t.tag_id): t for t in self.tags})
        put(self, "_costs", {(c.area_id, c.tenure, c.segment): c for c in self.costs})
        put(self, "_places", {p.place_id: p for p in self.places})
        stations: dict[str, list[StationAccess]] = {}
        for row in self.station_rows:
            stations.setdefault(row.area_id, []).append(row)
        put(self, "_stations", {area_id: tuple(rows) for area_id, rows in stations.items()})
        put(self, "_rows", {a: i for i, a in enumerate(self.travel_table.area_ids)})
        put(self, "_columns", {d: i for i, d in enumerate(self.travel_table.destination_ids)})
        put(self, "_placed", frozenset(t.tag_id for t in self.tags if t.score is not None))
        put(self, "_costed", frozenset((c.tenure, c.segment) for c in self.costs))

    def neighbourhood(self, area_id: str) -> Neighbourhood | None:
        return self._areas.get(area_id)

    def geometry(self, area_id: str) -> Geometry | None:
        return self._geometries.get(area_id)

    def feature(self, area_id: str, feature_id: FeatureId) -> FeatureValue | None:
        return self._features.get((area_id, feature_id))

    def tag(self, area_id: str, tag_id: TagId) -> TagValue | None:
        return self._tags.get((area_id, tag_id))

    def cost(self, area_id: str, tenure: Tenure, segment: Segment) -> CostEstimate | None:
        return self._costs.get((area_id, tenure, segment))

    def place(self, place_id: str) -> Place | None:
        return self._places.get(place_id)

    def travel(self, area_id: str, destination_id: str, mode: Mode, basis: PtBasis) -> Travel:
        row = self._rows.get(area_id)
        column = self._columns.get(destination_id)
        if row is None or column is None:
            return MISSING_TRAVEL
        matrix = self.travel_table.matrix(mode, basis)
        # A hand-built release may hold a matrix smaller than its ids say.
        if row >= len(matrix) or column >= len(matrix[row]):
            return MISSING_TRAVEL
        cell = matrix[row][column]
        if cell is None:
            return MISSING_TRAVEL
        if cell == BEYOND_CUTOFF_CELL:
            return BEYOND_CUTOFF_TRAVEL
        return Travel(status=TravelStatus.OK, minutes=cell)

    def stations(self, area_id: str) -> tuple[StationAccess, ...]:
        return self._stations.get(area_id, ())

    def origin(self, part: Part) -> Origin:
        if part is Part.NEIGHBOURHOODS:
            return self.neighbourhoods_origin
        if part is Part.STATIONS:
            return self.stations_origin
        return Origin(source_ids=self.travel_table.source_ids, as_of=self.travel_table.as_of)

    def cutoff(self, mode: Mode) -> int:
        return self.travel_table.cutoff_minutes.of(mode)

    def placed(self, tag_id: TagId) -> bool:
        return tag_id in self._placed

    def costed(self, tenure: Tenure, segment: Segment) -> bool:
        return (tenure, segment) in self._costed

    def documents(self) -> dict[str, object]:
        """The content of every file of this release, keyed by file name.

        The inverse of `parse_release`. Writing a release is serialising these,
        so the shape of a file is stated in one module and not two.
        """
        files = _Files(
            manifest=self.manifest,
            # The areas of a release always say where they came from. One built by hand
            # that does not is refused here, as any record that is not valid is.
            neighbourhoods=_NeighbourhoodsFile.model_validate(
                {
                    "source_ids": self.neighbourhoods_origin.source_ids,
                    "as_of": self.neighbourhoods_origin.as_of,
                    "neighbourhoods": self.neighbourhoods,
                }
            ),
            geometry=_GeometryFile(
                type="FeatureCollection",
                features=tuple(
                    _GeometryFeature(
                        type="Feature",
                        id=g.area_id,
                        properties=_GeometryProperties(area_id=g.area_id),
                        geometry=g.geometry,
                    )
                    for g in self.geometries
                ),
            ),
            catalogue=_CatalogueFile(
                catalogue_version=CATALOGUE_VERSION, metrics=self.metrics, vibes=self.vibes
            ),
            features=_FeaturesFile(rows=self.features),
            tags=_TagsFile(rows=self.tags),
            cost=_CostFile(rows=self.costs),
            destinations=_DestinationsFile(destinations=self.destinations),
            travel=self.travel_table,
            stations=_StationsFile(
                source_ids=self.stations_origin.source_ids,
                as_of=self.stations_origin.as_of,
                rows=self.station_rows,
            ),
            places=_PlacesFile(places=self.places),
        )
        return {name: model.model_dump(mode="json") for name, model in files.by_name().items()}


# The shape of each file. Private: outside this module a release is read through `Release`.


class _NeighbourhoodsFile(Record):
    source_ids: SourceIds
    as_of: str = Field(pattern=DATE_OR_MONTH_PATTERN)
    neighbourhoods: tuple[Neighbourhood, ...]


class _GeometryProperties(Record):
    area_id: AreaId


class _GeometryFeature(Record):
    type: Literal["Feature"]
    id: AreaId
    properties: _GeometryProperties
    geometry: Geometry


class _GeometryFile(Record):
    type: Literal["FeatureCollection"]
    features: tuple[_GeometryFeature, ...]


class _CatalogueFile(Record):
    catalogue_version: int
    metrics: tuple[Metric, ...]
    # The recipes the release was built with, so that it can be read alone.
    vibes: tuple[Tag, ...]


class _FeaturesFile(Record):
    rows: tuple[FeatureValue, ...]


class _TagsFile(Record):
    rows: tuple[TagValue, ...]


class _CostFile(Record):
    rows: tuple[CostEstimate, ...]


class _DestinationsFile(Record):
    destinations: tuple[Destination, ...]


class _StationsFile(Record):
    # Both are empty only in a preview that holds no station: `sources_are_stated`.
    source_ids: SourceIdsIfAny
    as_of: DateOrMonthIfAny
    rows: tuple[StationAccess, ...]


class _PlacesFile(Record):
    places: tuple[Place, ...]


@dataclass(frozen=True)
class _Files:
    """Every file of a release, validated for shape and in the order it was written."""

    manifest: Manifest
    neighbourhoods: _NeighbourhoodsFile
    geometry: _GeometryFile
    catalogue: _CatalogueFile
    features: _FeaturesFile
    tags: _TagsFile
    cost: _CostFile
    destinations: _DestinationsFile
    travel: TravelTable
    stations: _StationsFile
    places: _PlacesFile

    def by_name(self) -> dict[str, Record]:
        return {
            MANIFEST: self.manifest,
            NEIGHBOURHOODS: self.neighbourhoods,
            GEOMETRY: self.geometry,
            CATALOGUE: self.catalogue,
            FEATURES_FILE: self.features,
            TAGS_FILE: self.tags,
            COST: self.cost,
            DESTINATIONS: self.destinations,
            TRAVEL: self.travel,
            STATIONS: self.stations,
            PLACES: self.places,
        }

    def area_ids(self) -> frozenset[str]:
        return frozenset(n.area_id for n in self.neighbourhoods.neighbourhoods)

    def matrices(self) -> tuple[tuple[str, Mode, Matrix], ...]:
        return (
            ("pt_typical", Mode.PT, self.travel.pt_typical),
            ("pt_just_missed", Mode.PT, self.travel.pt_just_missed),
            ("cycle", Mode.CYCLE, self.travel.cycle),
            ("walk", Mode.WALK, self.travel.walk),
        )


_SHAPES: Mapping[str, type[Record]] = {
    MANIFEST: Manifest,
    NEIGHBOURHOODS: _NeighbourhoodsFile,
    GEOMETRY: _GeometryFile,
    CATALOGUE: _CatalogueFile,
    FEATURES_FILE: _FeaturesFile,
    TAGS_FILE: _TagsFile,
    COST: _CostFile,
    DESTINATIONS: _DestinationsFile,
    TRAVEL: TravelTable,
    STATIONS: _StationsFile,
    PLACES: _PlacesFile,
}

# A finding is the file and the row that broke the rule. It never holds a value.
Finding = tuple[str, str]
Rule = Callable[[_Files], Iterable[Finding]]


def versions_match(files: _Files) -> Iterator[Finding]:
    if files.manifest.schema_version != SCHEMA_VERSION:
        yield MANIFEST, "schema_version"
    if files.manifest.catalogue_version != CATALOGUE_VERSION:
        yield MANIFEST, "catalogue_version"
    if files.catalogue.catalogue_version != CATALOGUE_VERSION:
        yield CATALOGUE, "catalogue_version"


def synthetic_is_consistent(files: _Files) -> Iterator[Finding]:
    synthetic = files.manifest.synthetic
    if files.manifest.release_id.startswith(SYNTHETIC_PREFIX) != synthetic:
        yield MANIFEST, "release_id"
    if (files.manifest.city is City.SYN) != synthetic:
        yield MANIFEST, "city"
    ids: tuple[tuple[str, str, Sequence[str]], ...] = (
        (
            NEIGHBOURHOODS,
            "neighbourhoods",
            [n.area_id for n in files.neighbourhoods.neighbourhoods],
        ),
        (DESTINATIONS, "destinations", [d.destination_id for d in files.destinations.destinations]),
        (PLACES, "places", [p.place_id for p in files.places.places]),
        (STATIONS, "rows", [s.station_id for s in files.stations.rows]),
    )
    for file, rows, values in ids:
        for index, value in enumerate(values):
            if value.startswith(SYNTHETIC_PREFIX) != synthetic:
                yield file, f"{rows}[{index}]"
    # The reserved source says "this was made up". A real release may never
    # cite it, and a synthetic one may cite nothing else.
    for index, source in enumerate(files.manifest.sources):
        reserved = source.source_id == SYNTHETIC_SOURCE_ID
        if reserved != synthetic or (reserved and source.attribution != SYNTHETIC_ATTRIBUTION):
            yield MANIFEST, f"sources[{index}]"


def _repeated(keys: Sequence[Hashable]) -> Iterator[int]:
    seen: set[Hashable] = set()
    for index, key in enumerate(keys):
        if key in seen:
            yield index
        seen.add(key)


def _out_of_order(keys: Sequence[str]) -> Iterator[int]:
    """Positions that are not above the one before: a repeat, or a list that is not sorted."""
    for index in range(1, len(keys)):
        if keys[index] <= keys[index - 1]:
            yield index


def ids_are_unique(files: _Files) -> Iterator[Finding]:
    areas = files.neighbourhoods.neighbourhoods
    stations = files.stations.rows
    keyed: tuple[tuple[str, str, Sequence[Hashable]], ...] = (
        (MANIFEST, "sources", [s.source_id for s in files.manifest.sources]),
        (MANIFEST, "files", [f.name for f in files.manifest.files]),
        (NEIGHBOURHOODS, "neighbourhoods", [n.area_id for n in areas]),
        (NEIGHBOURHOODS, "neighbourhoods", [n.slug for n in areas]),
        (GEOMETRY, "features", [g.id for g in files.geometry.features]),
        (CATALOGUE, "metrics", [m.feature_id for m in files.catalogue.metrics]),
        (CATALOGUE, "vibes", [v.tag_id for v in files.catalogue.vibes]),
        (FEATURES_FILE, "rows", [(r.area_id, r.feature_id) for r in files.features.rows]),
        (TAGS_FILE, "rows", [(r.area_id, r.tag_id) for r in files.tags.rows]),
        (COST, "rows", [(r.area_id, r.tenure, r.segment) for r in files.cost.rows]),
        (DESTINATIONS, "destinations", [d.destination_id for d in files.destinations.destinations]),
        (STATIONS, "rows", [(s.area_id, s.station_id) for s in stations]),
        # At most one station is an area's nearest.
        (
            STATIONS,
            "rows",
            [s.area_id if s.nearest else (s.area_id, i) for i, s in enumerate(stations)],
        ),
        (PLACES, "places", [p.place_id for p in files.places.places]),
    )
    for file, rows, keys in keyed:
        for index in _repeated(keys):
            yield file, f"{rows}[{index}]"

    # An id names one station, whichever area's row it is read from.
    described: dict[str, tuple[str, tuple[str, ...], bool]] = {}
    for index, station in enumerate(stations):
        description = (station.name, station.lines, station.step_free)
        if described.setdefault(station.station_id, description) != description:
            yield STATIONS, f"rows[{index}]"

    # The lists the contract calls sorted. One check covers a repeat and a wrong order.
    ordered: list[tuple[str, str, Sequence[str]]] = [
        (TRAVEL, "area_ids", files.travel.area_ids),
        (TRAVEL, "destination_ids", files.travel.destination_ids),
        (TRAVEL, "source_ids", files.travel.source_ids),
        (NEIGHBOURHOODS, "source_ids", files.neighbourhoods.source_ids),
        (STATIONS, "source_ids", files.stations.source_ids),
    ]
    ordered += [
        (NEIGHBOURHOODS, f"neighbourhoods[{i}].neighbours", n.neighbours)
        for i, n in enumerate(areas)
    ]
    ordered += [
        (NEIGHBOURHOODS, f"neighbourhoods[{i}].named.source_ids", n.named.source_ids)
        for i, n in enumerate(areas)
        if n.named is not None
    ]
    ordered += [
        (CATALOGUE, f"metrics[{i}].source_ids", m.source_ids)
        for i, m in enumerate(files.catalogue.metrics)
    ]
    ordered += [
        (COST, f"rows[{i}].source_ids", r.source_ids) for i, r in enumerate(files.cost.rows)
    ]
    ordered += [(STATIONS, f"rows[{i}].lines", s.lines) for i, s in enumerate(stations)]
    for file, row, keys in ordered:
        for index in _out_of_order(keys):
            yield file, f"{row}[{index}]"


def _cited_sources(files: _Files) -> Iterator[tuple[str, str, str]]:
    for index, source_id in enumerate(files.neighbourhoods.source_ids):
        yield NEIGHBOURHOODS, f"source_ids[{index}]", source_id
    for index, source_id in enumerate(files.stations.source_ids):
        yield STATIONS, f"source_ids[{index}]", source_id
    for index, source_id in enumerate(files.travel.source_ids):
        yield TRAVEL, f"source_ids[{index}]", source_id
    for index, metric in enumerate(files.catalogue.metrics):
        for position, source_id in enumerate(metric.source_ids):
            yield CATALOGUE, f"metrics[{index}].source_ids[{position}]", source_id
    for index, row in enumerate(files.cost.rows):
        for position, source_id in enumerate(row.source_ids):
            yield COST, f"rows[{index}].source_ids[{position}]", source_id
    for index, place in enumerate(files.places.places):
        yield PLACES, f"places[{index}].source_id", place.source_id


def references_resolve(files: _Files) -> Iterator[Finding]:
    areas = files.area_ids()
    destinations = {d.destination_id for d in files.destinations.destinations}
    places = {p.place_id: p for p in files.places.places}
    carried = {m.feature_id for m in files.catalogue.metrics}
    vibes = {v.tag_id for v in files.catalogue.vibes}
    sources = {s.source_id for s in files.manifest.sources}

    for index, area in enumerate(files.neighbourhoods.neighbourhoods):
        for position, neighbour in enumerate(area.neighbours):
            if neighbour not in areas or neighbour == area.area_id:
                yield NEIGHBOURHOODS, f"neighbourhoods[{index}].neighbours[{position}]"
        # Who wrote a name is among the sources of the file, so that the fact of the area
        # cites them: a name is never written by a source the file does not state.
        for position, source_id in enumerate(area.named.source_ids if area.named else ()):
            if source_id not in files.neighbourhoods.source_ids:
                yield NEIGHBOURHOODS, f"neighbourhoods[{index}].named.source_ids[{position}]"
    for index, feature in enumerate(files.geometry.features):
        if feature.id not in areas or feature.properties.area_id != feature.id:
            yield GEOMETRY, f"features[{index}]"
    for index, row in enumerate(files.features.rows):
        if row.area_id not in areas or row.feature_id not in carried:
            yield FEATURES_FILE, f"rows[{index}]"
    for index, row in enumerate(files.tags.rows):
        if row.area_id not in areas or row.tag_id not in vibes:
            yield TAGS_FILE, f"rows[{index}]"
    in_areas: tuple[tuple[str, Sequence[str]], ...] = (
        (COST, [r.area_id for r in files.cost.rows]),
        (STATIONS, [r.area_id for r in files.stations.rows]),
    )
    for file, area_ids in in_areas:
        for index, area_id in enumerate(area_ids):
            if area_id not in areas:
                yield file, f"rows[{index}]"
    for index, area_id in enumerate(files.travel.area_ids):
        if area_id not in areas:
            yield TRAVEL, f"area_ids[{index}]"
    for index, destination_id in enumerate(files.travel.destination_ids):
        if destination_id not in destinations:
            yield TRAVEL, f"destination_ids[{index}]"
    for index, place in enumerate(files.places.places):
        if place.destination_id not in destinations:
            yield PLACES, f"places[{index}].destination_id"
        coarse = places.get(place.coarse_place_id)
        is_coarse = place.kind in (PlaceKind.STATION, PlaceKind.DISTRICT)
        if (
            coarse is None
            or coarse.kind not in (PlaceKind.STATION, PlaceKind.DISTRICT)
            # A coarse place names itself.
            or (is_coarse and coarse.place_id != place.place_id)
        ):
            yield PLACES, f"places[{index}].coarse_place_id"
    for file, row, source_id in _cited_sources(files):
        if source_id not in sources:
            yield file, row


# What core decides of a feature. A release repeats it so that it can be read alone.
DECIDED_BY_CORE = (
    "label",
    "short_label",
    "dimension",
    "unit",
    "polarity",
    "kind",
    "describes",
    "family",
    "method",
    "in_likeness",
)


def catalogue_matches_core(files: _Files) -> Iterator[Finding]:
    """A release names and measures each feature as core does, and ranks on none core shows only.

    A release may switch a feature off for ranking. It may not switch on one
    that core says is shown and never ranked on.
    """
    for index, metric in enumerate(files.catalogue.metrics):
        core = FEATURES[metric.feature_id]
        as_core = all(getattr(metric, name) == getattr(core, name) for name in DECIDED_BY_CORE)
        shown_only = metric.feature_id in RANKED_AS
        if not as_core or (shown_only and metric.rankable):
            yield CATALOGUE, f"metrics[{index}]"


def vibes_match_core(files: _Files) -> Iterator[Finding]:
    """A release carries the vibes its manifest says it does, each as core has it.

    The manifest says whether Gritty is among them. A recipe that differs
    from core's by a hundredth is refused, because the scores in the release
    were worked out with core's.
    """
    for index, vibe in enumerate(files.catalogue.vibes):
        if vibe != TAGS[vibe.tag_id]:
            yield CATALOGUE, f"vibes[{index}]"
    expected = {tag.tag_id for tag in tags_of(files.manifest.gritty_variant)}
    if {vibe.tag_id for vibe in files.catalogue.vibes} != expected:
        yield CATALOGUE, "vibes"


def rows_are_complete(files: _Files) -> Iterator[Finding]:
    areas = files.area_ids()
    feature_rows = {(r.area_id, r.feature_id) for r in files.features.rows}
    tag_rows = {(r.area_id, r.tag_id) for r in files.tags.rows}
    drawn = {g.id for g in files.geometry.features}
    for index, area in enumerate(files.neighbourhoods.neighbourhoods):
        # The row that is missing has no position, so the finding names the area's.
        row = f"neighbourhoods[{index}]"
        if any((area.area_id, m.feature_id) not in feature_rows for m in files.catalogue.metrics):
            yield FEATURES_FILE, row
        if any((area.area_id, vibe.tag_id) not in tag_rows for vibe in files.catalogue.vibes):
            yield TAGS_FILE, row
        if area.area_id not in drawn:
            yield GEOMETRY, row
    destinations = {d.destination_id for d in files.destinations.destinations}
    if frozenset(files.travel.area_ids) != areas:
        yield TRAVEL, "area_ids"
    routed = set(files.travel.destination_ids)
    # A preview that has routed no journey holds no time, whatever ends its places name:
    # a journey to one is estimated from distance, or is said to be missing.
    if routed != destinations and (routed or not files.manifest.preview):
        yield TRAVEL, "destination_ids"
    for name, _, matrix in files.matrices():
        if len(matrix) != len(files.travel.area_ids):
            yield TRAVEL, name
        for index, cells in enumerate(matrix):
            if len(cells) != len(files.travel.destination_ids):
                yield TRAVEL, f"{name}[{index}]"


def _within_reach(point: Point, of: Point) -> bool:
    return abs(point[0] - of[0]) <= REACH and abs(point[1] - of[1]) <= REACH


def _points_of(geometry: Geometry) -> Iterator[Point]:
    polygons = (
        cast(tuple[PolygonRings, ...], geometry.coordinates)
        if geometry.type is GeometryType.MULTI_POLYGON
        else (cast(PolygonRings, geometry.coordinates),)
    )
    for rings in polygons:
        for ring in rings:
            yield from ring


def _figures_are_in_range(files: _Files) -> Iterator[Finding]:
    """A figure is a share of the whole, from 0 to 100, or is not below nought."""
    unit = {metric.feature_id: metric.unit for metric in files.catalogue.metrics}
    for index, row in enumerate(files.features.rows):
        if row.value is None or row.feature_id not in unit:
            continue
        if row.value < 0 or (unit[row.feature_id] == PERCENT and row.value > 100):
            yield FEATURES_FILE, f"rows[{index}].value"


def _areas_are_where_they_are_drawn(files: _Files) -> Iterator[Finding]:
    """An outline lies round the point inside its area, and neighbours lie near each other.

    It holds a release to itself and to no place on the map, so a made-up city
    may be drawn in open sea. What it catches is one area drawn, or placed,
    far from where the rest of the release says it is.
    """
    inside = {area.area_id: area.centroid for area in files.neighbourhoods.neighbourhoods}
    for index, area in enumerate(files.neighbourhoods.neighbourhoods):
        near = (inside[other] for other in area.neighbours if other in inside)
        if not all(_within_reach(point, area.centroid) for point in near):
            yield NEIGHBOURHOODS, f"neighbourhoods[{index}].centroid"
        # Where its homes stand is held to the area as its outline is.
        if area.homes_at is not None and not _within_reach(area.homes_at, area.centroid):
            yield NEIGHBOURHOODS, f"neighbourhoods[{index}].homes_at"
    for index, feature in enumerate(files.geometry.features):
        if feature.id in inside and not all(
            _within_reach(point, inside[feature.id]) for point in _points_of(feature.geometry)
        ):
            yield GEOMETRY, f"features[{index}]"


def confidence_of(sales: int) -> Confidence:
    """What a median that rests on so many sales is said to rest on: `high` from 50 sales up."""
    return Confidence.HIGH if sales >= MANY_SALES else Confidence.MEDIUM


def _cost_holds_together(row: CostEstimate) -> bool:
    """Whether a cost is a range in order, or one number that says it is no more than that.

    One quartile with no other is no range. A row with no range is a price:
    no source gives a rent as one number, and no sentence says one. Where it
    gives no count of the sales it rests on, it says that what it rests on is
    not stated. Where it gives one, it gives the first month of the sales
    too, the count is no fewer than `FEWEST_SALES`, and what it rests on is
    what the count makes it. A row with a range says what it rests on, and
    holds no count.
    """
    lower, upper = row.lower_quartile, row.upper_quartile
    if (row.sales is None) is not (row.since is None):
        return False
    if lower is None or upper is None:
        if row.sales is None:
            rests_on = Confidence.UNSTATED
        elif row.sales < FEWEST_SALES or row.since is None or row.since > row.as_of:
            return False
        else:
            rests_on = confidence_of(row.sales)
        return lower is upper and row.confidence is rests_on and row.tenure is Tenure.BUY
    return (
        lower <= row.median <= upper
        and row.confidence is not Confidence.UNSTATED
        and row.sales is None
    )


def values_are_in_range(files: _Files) -> Iterator[Finding]:
    yield from _figures_are_in_range(files)
    yield from _areas_are_where_they_are_drawn(files)
    for index, row in enumerate(files.cost.rows):
        if not _cost_holds_together(row) or row.segment not in segments_for(row.tenure):
            yield COST, f"rows[{index}]"
    for name, mode, matrix in files.matrices():
        cutoff = files.travel.cutoff_minutes.of(mode)
        for index, cells in enumerate(matrix):
            for column, cell in enumerate(cells):
                if cell is not None and cell > cutoff:
                    yield TRAVEL, f"{name}[{index}][{column}]"
    pairs = zip(files.travel.pt_typical, files.travel.pt_just_missed, strict=False)
    for index, (typical_row, missed_row) in enumerate(pairs):
        for column, (typical, missed) in enumerate(zip(typical_row, missed_row, strict=False)):
            # Missing a service can only make a journey longer.
            if typical is not None and missed is not None and 0 <= missed < typical:
                yield TRAVEL, f"pt_just_missed[{index}][{column}]"
    for index, station in enumerate(files.stations.rows):
        if not station.nearest and station.walk_minutes > NEARBY_STATION_MINUTES:
            yield STATIONS, f"rows[{index}].walk_minutes"


def null_means_null(files: _Files) -> Iterator[Finding]:
    for index, row in enumerate(files.features.rows):
        # Below half coverage the source saw too little of the area to give a value.
        if (row.value is None) != (row.percentile is None) or (
            row.value is not None and row.coverage < FEATURE_MIN_COVERAGE
        ):
            yield FEATURES_FILE, f"rows[{index}]"
    for index, row in enumerate(files.tags.rows):
        if (row.raw is None) != (row.score is None) or (
            row.raw is not None and row.coverage < TAG_MIN_COVERAGE_HUNDREDTHS / 100
        ):
            yield TAGS_FILE, f"rows[{index}]"


def bands_match_raw(files: _Files) -> Iterator[Finding]:
    """A band is worked out by `band_of` from the raw values, and by nothing else.

    It is unknown exactly when `raw` is, and the spread holds it. A release
    that holds a band of its own making is refused. It holds the band to the
    raw value and no more: `scores_match_raw`, `raw_matches_recipe` and
    `percentiles_match_values` hold the rest, so that what is shown can never
    part from what is ranked on.
    """
    rankable = {n.area_id: n.rankable for n in files.neighbourhoods.neighbourhoods}
    by_tag: dict[TagId, list[tuple[int, TagValue]]] = {}
    for index, row in enumerate(files.tags.rows):
        by_tag.setdefault(row.tag_id, []).append((index, row))
    for rows in by_tag.values():
        bands = band_of(
            [row.raw for _, row in rows], [rankable.get(row.area_id, False) for _, row in rows]
        )
        for (index, row), band in zip(rows, bands, strict=True):
            low, high = row.spread_low, row.spread_high
            placed = (
                row.band is not None
                and low is not None
                and high is not None
                and low <= row.band <= high
            )
            unknown = row.band is None and low is None and high is None
            if row.band != band or not (unknown if row.raw is None else placed):
                yield TAGS_FILE, f"rows[{index}]"


def sources_are_stated(files: _Files) -> Iterator[Finding]:
    """An empty list or date is caught when the file is read. This is what is left.

    A tag's fact cites the sources of the features in its formula that had a
    value. A tag with a score and no such feature would be a fact with no source.

    The journeys and the stations state their sources and their date once, for
    the file. Either may state neither, if it holds nothing and the release
    says it is a preview: a release that has routed no journey has no timetable
    to cite, and naming one would be making a source up. One that states a
    source and no date, or a date and no source, is refused whatever it holds.
    """
    valued = {(r.area_id, r.feature_id) for r in files.features.rows if r.value is not None}
    for index, row in enumerate(files.tags.rows):
        if row.score is not None and not any(
            (row.area_id, term.feature_id) in valued for term in TAGS[row.tag_id].terms
        ):
            yield TAGS_FILE, f"rows[{index}]"
    parts = (
        (TRAVEL, files.travel.source_ids, files.travel.as_of, files.travel.destination_ids),
        (STATIONS, files.stations.source_ids, files.stations.as_of, files.stations.rows),
    )
    for file, source_ids, as_of, held in parts:
        sourced, dated = bool(source_ids), as_of is not None
        if sourced and dated:
            continue
        if sourced != dated or held or not files.manifest.preview:
            yield file, "as_of" if sourced else "source_ids"


def neighbours_are_symmetric(files: _Files) -> Iterator[Finding]:
    neighbours = {n.area_id: set(n.neighbours) for n in files.neighbourhoods.neighbourhoods}
    for index, area in enumerate(files.neighbourhoods.neighbourhoods):
        for position, other in enumerate(area.neighbours):
            if area.area_id not in neighbours.get(other, {area.area_id}):
                yield NEIGHBOURHOODS, f"neighbourhoods[{index}].neighbours[{position}]"


def finished_release_is_whole(files: _Files) -> Iterator[Finding]:
    """A release that does not say it is a preview holds every part a person is shown.

    A release with no journey, no place to reach, no cost or no station is not
    finished. It once passed as one, if its empty files named a source. Now
    it says it is a preview, or it is refused.
    """
    held = (
        files.destinations.destinations,
        files.places.places,
        files.cost.rows,
        files.stations.rows,
    )
    if not files.manifest.preview and not all(held):
        yield MANIFEST, "preview"


# A release is written with six decimals, so two figures that are the same
# figure differ by less than this.
_SAME_WITHIN = 1e-6


def _same(held: float | None, worked_out: float | None) -> bool:
    """Whether a figure a release holds is the figure core works out."""
    if held is None or worked_out is None:
        return held is worked_out
    return abs(held - worked_out) < _SAME_WITHIN


def _by_key[K, R](rows: Sequence[R], key: Callable[[R], K]) -> dict[K, list[tuple[int, R]]]:
    found: dict[K, list[tuple[int, R]]] = {}
    for index, row in enumerate(rows):
        found.setdefault(key(row), []).append((index, row))
    return found


def _percentiles_part(
    file: str, rows: Sequence[tuple[int, float | None, float | None, str]], files: _Files
) -> Iterator[Finding]:
    """The rows whose percentile is not the one `percentile_of` gives their figures."""
    rankable = {n.area_id: n.rankable for n in files.neighbourhoods.neighbourhoods}
    worked_out = percentile_of(
        [figure for _, figure, _, _ in rows],
        [rankable.get(area_id, False) for _, _, _, area_id in rows],
    )
    for (index, _, held, _), percentile in zip(rows, worked_out, strict=True):
        if not _same(held, percentile):
            yield file, f"rows[{index}]"


def percentiles_match_values(files: _Files) -> Iterator[Finding]:
    """A percentile is worked out by `percentile_of` from the values of the release.

    An area is ranked on the percentile and shown the value. A percentile
    that stands at the far end from its value would rank an area on one
    figure and print another.
    """
    for rows in _by_key(files.features.rows, lambda row: row.feature_id).values():
        held = [(index, row.value, row.percentile, row.area_id) for index, row in rows]
        yield from _percentiles_part(FEATURES_FILE, held, files)


def raw_matches_recipe(files: _Files) -> Iterator[Finding]:
    """A vibe's raw value and coverage are what `tag_raw` makes of the release's own features.

    So an area can never be placed on a vibe by figures that are not its own,
    and the share of the recipe a band rests on is the share that was there.
    """
    percentiles = {(row.area_id, row.feature_id): row.percentile for row in files.features.rows}
    for index, row in enumerate(files.tags.rows):
        parts = {
            term.feature_id: percentiles.get((row.area_id, term.feature_id))
            for term in TAGS[row.tag_id].terms
        }
        worked_out = tag_raw(row.tag_id, parts)
        if not (_same(row.raw, worked_out.raw) and _same(row.coverage, worked_out.coverage)):
            yield TAGS_FILE, f"rows[{index}]"


def scores_match_raw(files: _Files) -> Iterator[Finding]:
    """A vibe's score is the percentile of its raw value, by `percentile_of`.

    `rank()` reads the score, and a page shows the band of the raw value. A
    score of a release's own making would rank an area where no page shows it.
    """
    for rows in _by_key(files.tags.rows, lambda row: row.tag_id).values():
        held = [(index, row.raw, row.score, row.area_id) for index, row in rows]
        yield from _percentiles_part(TAGS_FILE, held, files)


RULES: tuple[Rule, ...] = (
    versions_match,
    synthetic_is_consistent,
    ids_are_unique,
    references_resolve,
    catalogue_matches_core,
    vibes_match_core,
    rows_are_complete,
    values_are_in_range,
    null_means_null,
    bands_match_raw,
    sources_are_stated,
    neighbours_are_symmetric,
    finished_release_is_whole,
    percentiles_match_values,
    raw_matches_recipe,
    scores_match_raw,
)

_RANGE_ERRORS = frozenset(
    {"greater_than", "greater_than_equal", "less_than", "less_than_equal", "finite_number"}
)
_SOURCE_FIELDS = frozenset({"source_ids", "source_id", "as_of", "vintage"})
_CATALOGUE_FIELDS = frozenset({"feature_id", "tag_id"})


def _row(loc: tuple[int | str, ...]) -> str:
    parts = ""
    for part in loc:
        parts += f"[{part}]" if isinstance(part, int) else f".{part}"
    return parts.lstrip(".")


def _rule_for(loc: tuple[int | str, ...], kind: str) -> str:
    """Which rule of the contract a badly shaped field broke, from where it is and how it failed."""
    names = [part for part in loc if isinstance(part, str)]
    last = names[-1] if names else ""
    if last in _SOURCE_FIELDS:
        return sources_are_stated.__name__
    if last in _CATALOGUE_FIELDS and kind == "enum":
        return catalogue_matches_core.__name__
    if kind in _RANGE_ERRORS:
        return values_are_in_range.__name__
    return "shape_is_valid"


def _shaped(name: str, document: object) -> Record:
    try:
        return _SHAPES[name].model_validate(document)
    except ValidationError as error:
        # Only where and how. The message and the input can repeat a value.
        first = error.errors(include_url=False, include_context=False, include_input=False)[0]
        loc = first["loc"]
        if first["type"] == "extra_forbidden":
            # The name of a field that should not be there is itself something the file said.
            loc = loc[:-1]
        raise ReleaseError(name, _rule_for(loc, first["type"]), _row(loc)) from None


def parse_release(documents: Mapping[str, object]) -> InMemoryRelease:
    """Turn the parsed content of every file, keyed by file name, into a release.

    The only parser. It refuses the release at the first rule that is broken.
    """
    for name in _SHAPES:
        if name not in documents:
            raise ReleaseError(name, "files_are_expected")
    for name in sorted(documents):
        if name not in _SHAPES:
            raise ReleaseError(name, "files_are_expected")

    shaped = {name: _shaped(name, documents[name]) for name in _SHAPES}
    files = _Files(
        manifest=cast(Manifest, shaped[MANIFEST]),
        neighbourhoods=cast(_NeighbourhoodsFile, shaped[NEIGHBOURHOODS]),
        geometry=cast(_GeometryFile, shaped[GEOMETRY]),
        catalogue=cast(_CatalogueFile, shaped[CATALOGUE]),
        features=cast(_FeaturesFile, shaped[FEATURES_FILE]),
        tags=cast(_TagsFile, shaped[TAGS_FILE]),
        cost=cast(_CostFile, shaped[COST]),
        destinations=cast(_DestinationsFile, shaped[DESTINATIONS]),
        travel=cast(TravelTable, shaped[TRAVEL]),
        stations=cast(_StationsFile, shaped[STATIONS]),
        places=cast(_PlacesFile, shaped[PLACES]),
    )
    for rule in RULES:
        for file, row in rule(files):
            raise ReleaseError(file, getattr(rule, "__name__", "rule"), row)

    return InMemoryRelease(
        manifest=files.manifest,
        neighbourhoods=files.neighbourhoods.neighbourhoods,
        neighbourhoods_origin=Origin(
            source_ids=files.neighbourhoods.source_ids, as_of=files.neighbourhoods.as_of
        ),
        travel_table=files.travel,
        stations_origin=Origin(source_ids=files.stations.source_ids, as_of=files.stations.as_of),
        metrics=files.catalogue.metrics,
        features=files.features.rows,
        tags=files.tags.rows,
        costs=files.cost.rows,
        destinations=files.destinations.destinations,
        places=files.places.places,
        station_rows=files.stations.rows,
        geometries=tuple(
            AreaGeometry(area_id=f.id, geometry=f.geometry) for f in files.geometry.features
        ),
        vibes=files.catalogue.vibes,
    )


def _refuse_constant(_: str) -> Any:
    raise ValueError("NaN and Infinity are not JSON")


def _parsed(name: str, content: bytes) -> object:
    try:
        return json.loads(content.decode("utf-8"), parse_constant=_refuse_constant)
    except ValueError:
        raise ReleaseError(name, "json_is_valid") from None


def open_release(folder_name: str, files: Mapping[str, bytes]) -> InMemoryRelease:
    """Check the bytes of every file in a release folder against its manifest, then parse them.

    It reads no file itself: the caller passes the bytes, keyed by file name.
    A release never changes once written, so a file that does not match the
    checksum the manifest holds for it is refused.
    """
    if MANIFEST not in files:
        raise ReleaseError(MANIFEST, "files_match_manifest")
    manifest_document = _parsed(MANIFEST, files[MANIFEST])
    manifest = cast(Manifest, _shaped(MANIFEST, manifest_document))
    if manifest.release_id != folder_name:
        raise ReleaseError(MANIFEST, "release_id_matches_folder", "release_id")

    listed = {entry.name: entry for entry in manifest.files}
    # An extra file and a missing one are refused alike.
    for name in sorted((set(files) - {MANIFEST}) ^ set(listed)):
        raise ReleaseError(name, "files_match_manifest")
    documents: dict[str, object] = {MANIFEST: manifest_document}
    for name in sorted(listed):
        content = files[name]
        entry = listed[name]
        if len(content) != entry.bytes or hashlib.sha256(content).hexdigest() != entry.sha256:
            raise ReleaseError(name, "files_match_manifest")
        documents[name] = _parsed(name, content)
    return parse_release(documents)


def _hashes(beside: Mapping[str, bytes]) -> Hashes:
    try:
        return Hashes.model_validate(_parsed(HASHES, beside[HASHES]))
    except ValidationError:
        # Only that it is not shaped as the hashes of a build. Nothing it holds is repeated.
        raise ReleaseError(HASHES, "shape_is_valid") from None


def open_served(
    folder_name: str, files: Mapping[str, bytes], beside: Mapping[str, bytes] | None
) -> InMemoryRelease:
    """The release as it may be served: opened, and held to what it was built with.

    `beside` is the bytes of the hashes of the build, of its evidence and of
    its lock, by file name, as they stand in the folder beside the release. A
    made-up release is built from no file, so nothing is asked of it. A
    release that is not made up is refused unless all three are there, the
    hashes are of this release, and each of the manifest, the evidence and the
    lock still has the hash it had when it was built.

    Nothing here reads the evidence. That it stands behind every fact is
    checked when the release is built, and by `burro-release check`. What is
    held here is that the release and the evidence are the ones that were
    checked.
    """
    release = open_release(folder_name, files)
    if release.manifest.synthetic:
        return release
    held = beside or {}
    for name in (HASHES, EVIDENCE, LOCK):
        if name not in held:
            raise ReleaseError(name, "real_release_has_its_build")
    hashes = _hashes(held)
    if hashes.release_id != release.manifest.release_id:
        raise ReleaseError(HASHES, "build_is_of_this_release", "release_id")
    expected = (
        (MANIFEST, files[MANIFEST], hashes.manifest_sha256),
        (EVIDENCE, held[EVIDENCE], hashes.evidence_sha256),
        (LOCK, held[LOCK], hashes.lock_sha256),
    )
    for name, content, sha256 in expected:
        if hashlib.sha256(content).hexdigest() != sha256:
            raise ReleaseError(name, "build_is_as_it_was_written")
    return release
