"""The data release: its records, the protocol ranking reads it through, and the one parser.

A release is data and nothing else. `parse_release` and `open_release` do all
the checking, so the pipeline that writes a release and the API that loads one
cannot come to disagree about what a valid release is. Neither opens a file:
the caller reads the bytes and hands them over.
"""

import hashlib
import json
from collections.abc import Callable, Hashable, Iterable, Iterator, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Annotated, Any, Literal, Protocol, Self, cast

from pydantic import Field, StrictBool, ValidationError, model_validator

from burro_core._record import Record
from burro_core.catalogue import CATALOGUE_VERSION, FEATURES, TAG_MIN_COVERAGE_HUNDREDTHS, TAGS
from burro_core.ids import (
    DATE_OR_MONTH_PATTERN,
    DATE_PATTERN,
    MONTH_PATTERN,
    SLUG_PATTERN,
    SYNTHETIC_PREFIX,
    SYNTHETIC_SOURCE_ID,
    TIMESTAMP_PATTERN,
    AreaId,
    City,
    Confidence,
    DestinationId,
    Dimension,
    FeatureId,
    GeometryType,
    Mode,
    NativeResolution,
    Part,
    PlaceId,
    PlaceKind,
    Polarity,
    PtBasis,
    ReleaseId,
    Segment,
    SourceId,
    StationId,
    TagId,
    Tenure,
    TravelStatus,
    segments_for,
)

SCHEMA_VERSION = 1
SYNTHETIC_ATTRIBUTION = "Synthetic data generated by Burro for testing. It describes no real place."

# Below this share of an area, the source did not cover enough of it to give a value.
FEATURE_MIN_COVERAGE = 0.5
# Beyond the nearest, an area lists only the stations within this walk.
NEARBY_STATION_MINUTES = 10
# The cell of a travel matrix that says "no journey within the cutoff".
BEYOND_CUTOFF_CELL = -1

MANIFEST = "manifest.json"
NEIGHBOURHOODS = "neighbourhoods.json"
GEOMETRY = "geometry.json"
CATALOGUE = "catalogue.json"
FEATURES_FILE = "features.json"
TAGS_FILE = "tags.json"
COST = "cost.json"
DESTINATIONS = "destinations.json"
TRAVEL = "travel.json"
STATIONS = "stations.json"
PLACES = "places.json"

DATA_FILES = (
    NEIGHBOURHOODS,
    GEOMETRY,
    CATALOGUE,
    FEATURES_FILE,
    TAGS_FILE,
    COST,
    DESTINATIONS,
    TRAVEL,
    STATIONS,
    PLACES,
)


class ReleaseError(Exception):
    """A release broke a rule. Names the file, the row and the rule, and never a value."""

    def __init__(self, file: str, rule: str, row: str = "") -> None:
        self.file = file
        self.rule = rule
        self.row = row
        super().__init__(f"{file}: {row}: {rule}" if row else f"{file}: {rule}")


Share = Annotated[float, Field(ge=0, le=1, allow_inf_nan=False)]
Percentile = Annotated[float, Field(ge=0, le=100, allow_inf_nan=False)]
Point = tuple[
    Annotated[float, Field(ge=-180, le=180, allow_inf_nan=False)],
    Annotated[float, Field(ge=-90, le=90, allow_inf_nan=False)],
]
Text = Annotated[str, Field(min_length=1)]
SourceIds = Annotated[tuple[SourceId, ...], Field(min_length=1)]
Pounds = Annotated[int, Field(ge=0)]
Cell = Annotated[int, Field(ge=BEYOND_CUTOFF_CELL)] | None
Matrix = tuple[tuple[Cell, ...], ...]


class Source(Record):
    source_id: SourceId
    name: Text
    publisher: Text
    licence: Text
    attribution: Text
    url: str
    retrieved_on: str = Field(pattern=DATE_PATTERN)


class FileEntry(Record):
    name: Text
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    bytes: int = Field(ge=0)


class Counts(Record):
    neighbourhoods: int = Field(ge=0)
    rankable: int = Field(ge=0)
    destinations: int = Field(ge=0)
    places: int = Field(ge=0)
    stations: int = Field(ge=0)


class Manifest(Record):
    release_id: ReleaseId
    schema_version: int
    # An input to the builder, never read from the clock, so a rebuild is byte-identical.
    built_at: str = Field(pattern=TIMESTAMP_PATTERN)
    catalogue_version: int
    synthetic: StrictBool
    city: City
    seed: int | None
    sources: tuple[Source, ...]
    files: tuple[FileEntry, ...]
    counts: Counts


class Neighbourhood(Record):
    area_id: AreaId
    slug: str = Field(pattern=SLUG_PATTERN)
    name: Text
    borough: Text
    aliases: tuple[Text, ...]
    centroid: Point
    # The pipeline decides; core only reads.
    rankable: StrictBool
    neighbours: tuple[AreaId, ...]


class Metric(Record):
    """A feature this release carries. Core decides what it is; the release says where from."""

    feature_id: FeatureId
    label: str
    dimension: Dimension
    unit: str
    polarity: Polarity
    native_resolution: NativeResolution
    source_ids: SourceIds
    vintage: Text
    # False switches the feature off for ranking in this release. Its values are still shown.
    rankable: StrictBool
    definition: Text


class FeatureValue(Record):
    area_id: AreaId
    feature_id: FeatureId
    value: Annotated[float, Field(allow_inf_nan=False)] | None
    percentile: Percentile | None
    coverage: Share


class TagValue(Record):
    area_id: AreaId
    tag_id: TagId
    raw: Share | None
    score: Percentile | None
    coverage: Share


class CostEstimate(Record):
    area_id: AreaId
    tenure: Tenure
    segment: Segment
    lower_quartile: Pounds
    median: Pounds
    upper_quartile: Pounds
    confidence: Confidence
    as_of: str = Field(pattern=MONTH_PATTERN)
    source_ids: SourceIds


class Destination(Record):
    destination_id: DestinationId
    centroid: Point


class Travel(Record):
    """One journey time. A time that is not known is `None`, and never zero."""

    status: TravelStatus
    minutes: int | None

    @model_validator(mode="after")
    def _minutes_only_when_ok(self) -> Self:
        if (self.status is TravelStatus.OK) != (self.minutes is not None):
            raise ValueError("minutes is set exactly when status is ok")
        return self


MISSING_TRAVEL = Travel(status=TravelStatus.MISSING, minutes=None)
BEYOND_CUTOFF_TRAVEL = Travel(status=TravelStatus.BEYOND_CUTOFF, minutes=None)


class StationAccess(Record):
    area_id: AreaId
    station_id: StationId
    name: Text
    walk_minutes: int = Field(ge=0)
    lines: Annotated[tuple[Text, ...], Field(min_length=1)]
    step_free: StrictBool
    nearest: StrictBool


class Place(Record):
    place_id: PlaceId
    name: Text
    aliases: tuple[Text, ...]
    kind: PlaceKind
    destination_id: DestinationId
    # A station or district standing in for this place in a shared link.
    coarse_place_id: PlaceId
    centroid: Point
    source_id: SourceId


class Origin(Record):
    """Where one whole file came from, and when."""

    source_ids: SourceIds
    as_of: str = Field(pattern=DATE_OR_MONTH_PATTERN)


Ring = Annotated[tuple[Point, ...], Field(min_length=4)]
PolygonRings = Annotated[tuple[Ring, ...], Field(min_length=1)]


class Geometry(Record):
    """A GeoJSON geometry object: a polygon or a multipolygon, in WGS84."""

    type: GeometryType
    coordinates: PolygonRings | Annotated[tuple[PolygonRings, ...], Field(min_length=1)]

    @model_validator(mode="after")
    def _coordinates_suit_the_type(self) -> Self:
        # A polygon's first ring holds points; a multipolygon's first member holds rings.
        nested = isinstance(self.coordinates[0][0][0], tuple)
        if nested != (self.type is GeometryType.MULTI_POLYGON):
            raise ValueError("coordinates do not suit the geometry type")
        return self


class AreaGeometry(Record):
    area_id: AreaId
    geometry: Geometry


class Cutoffs(Record):
    """The longest journey the release routed, by mode. Anything longer is `beyond_cutoff`."""

    # No shorter than the shortest cap a commute may have, so every mode can be asked for.
    pt: int = Field(ge=10, le=1440)
    cycle: int = Field(ge=10, le=1440)
    walk: int = Field(ge=10, le=1440)

    def of(self, mode: Mode) -> int:
        return {Mode.PT: self.pt, Mode.CYCLE: self.cycle, Mode.WALK: self.walk}[mode]


class TravelTable(Record):
    """`travel.json` as it is written: four matrices, rows by area and columns by destination.

    A cell is minutes, `-1` for no journey within the cutoff, or `None` for not
    computed. The two spellings exist only here; `Release.travel()` returns a
    `Travel` and nothing outside this module sees a `-1`.
    """

    source_ids: SourceIds
    as_of: str = Field(pattern=DATE_OR_MONTH_PATTERN)
    area_ids: tuple[AreaId, ...]
    destination_ids: tuple[DestinationId, ...]
    cutoff_minutes: Cutoffs
    pt_typical: Matrix
    pt_just_missed: Matrix
    cycle: Matrix
    walk: Matrix

    def matrix(self, mode: Mode, basis: PtBasis) -> Matrix:
        if mode is Mode.CYCLE:
            return self.cycle
        if mode is Mode.WALK:
            return self.walk
        return self.pt_typical if basis is PtBasis.TYPICAL else self.pt_just_missed


class Release(Protocol):
    """What ranking, facts and the interpreters read a release through.

    The three tuples are ordered by id, and `stations` nearest first. `None`
    means the id is unknown to this release, or for `cost` that there is no
    estimate. `travel` never returns `None`: for a time that is not in the
    release, and for an id it does not know, it answers `missing`.
    """

    @property
    def manifest(self) -> Manifest: ...
    @property
    def neighbourhoods(self) -> tuple[Neighbourhood, ...]: ...
    @property
    def metrics(self) -> tuple[Metric, ...]: ...
    @property
    def places(self) -> tuple[Place, ...]: ...
    def neighbourhood(self, area_id: str) -> Neighbourhood | None: ...
    def geometry(self, area_id: str) -> Geometry | None: ...
    def feature(self, area_id: str, feature_id: FeatureId) -> FeatureValue | None: ...
    def tag(self, area_id: str, tag_id: TagId) -> TagValue | None: ...
    def cost(self, area_id: str, tenure: Tenure, segment: Segment) -> CostEstimate | None: ...
    def place(self, place_id: str) -> Place | None: ...
    def travel(self, area_id: str, destination_id: str, mode: Mode, basis: PtBasis) -> Travel: ...
    def stations(self, area_id: str) -> tuple[StationAccess, ...]: ...
    def origin(self, part: Part) -> Origin: ...
    def cutoff(self, mode: Mode) -> int: ...


def _station_order(row: StationAccess) -> tuple[str, bool, int, str]:
    return (row.area_id, not row.nearest, row.walk_minutes, row.station_id)


@dataclass(frozen=True)
class InMemoryRelease:
    """A whole release held as records. The one implementation of `Release` in this build.

    Every tuple is put in one order on construction, so two releases built from
    the same rows in a different order are equal and are written the same. The
    constructor checks nothing: `parse_release` does, and a release built by
    hand in a test is as good as its author.
    """

    manifest: Manifest
    neighbourhoods: tuple[Neighbourhood, ...]
    neighbourhoods_origin: Origin
    travel_table: TravelTable
    stations_origin: Origin
    metrics: tuple[Metric, ...] = ()
    features: tuple[FeatureValue, ...] = ()
    tags: tuple[TagValue, ...] = ()
    costs: tuple[CostEstimate, ...] = ()
    destinations: tuple[Destination, ...] = ()
    places: tuple[Place, ...] = ()
    station_rows: tuple[StationAccess, ...] = ()
    geometries: tuple[AreaGeometry, ...] = ()

    _areas: Mapping[str, Neighbourhood] = field(init=False, repr=False, compare=False)
    _geometries: Mapping[str, Geometry] = field(init=False, repr=False, compare=False)
    _features: Mapping[tuple[str, FeatureId], FeatureValue] = field(
        init=False, repr=False, compare=False
    )
    _tags: Mapping[tuple[str, TagId], TagValue] = field(init=False, repr=False, compare=False)
    _costs: Mapping[tuple[str, Tenure, Segment], CostEstimate] = field(
        init=False, repr=False, compare=False
    )
    _places: Mapping[str, Place] = field(init=False, repr=False, compare=False)
    _stations: Mapping[str, tuple[StationAccess, ...]] = field(
        init=False, repr=False, compare=False
    )
    _rows: Mapping[str, int] = field(init=False, repr=False, compare=False)
    _columns: Mapping[str, int] = field(init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        put = object.__setattr__
        put(self, "neighbourhoods", tuple(sorted(self.neighbourhoods, key=lambda n: n.area_id)))
        put(self, "metrics", tuple(sorted(self.metrics, key=lambda m: m.feature_id)))
        put(self, "features", tuple(sorted(self.features, key=lambda f: (f.area_id, f.feature_id))))
        put(self, "tags", tuple(sorted(self.tags, key=lambda t: (t.area_id, t.tag_id))))
        put(
            self,
            "costs",
            tuple(sorted(self.costs, key=lambda c: (c.area_id, c.tenure, c.segment))),
        )
        put(self, "destinations", tuple(sorted(self.destinations, key=lambda d: d.destination_id)))
        put(self, "places", tuple(sorted(self.places, key=lambda p: p.place_id)))
        put(self, "station_rows", tuple(sorted(self.station_rows, key=_station_order)))
        put(self, "geometries", tuple(sorted(self.geometries, key=lambda g: g.area_id)))

        put(self, "_areas", {n.area_id: n for n in self.neighbourhoods})
        put(self, "_geometries", {g.area_id: g.geometry for g in self.geometries})
        put(self, "_features", {(f.area_id, f.feature_id): f for f in self.features})
        put(self, "_tags", {(t.area_id, t.tag_id): t for t in self.tags})
        put(self, "_costs", {(c.area_id, c.tenure, c.segment): c for c in self.costs})
        put(self, "_places", {p.place_id: p for p in self.places})
        stations: dict[str, list[StationAccess]] = {}
        for row in self.station_rows:
            stations.setdefault(row.area_id, []).append(row)
        put(self, "_stations", {area_id: tuple(rows) for area_id, rows in stations.items()})
        put(self, "_rows", {a: i for i, a in enumerate(self.travel_table.area_ids)})
        put(self, "_columns", {d: i for i, d in enumerate(self.travel_table.destination_ids)})

    def neighbourhood(self, area_id: str) -> Neighbourhood | None:
        return self._areas.get(area_id)

    def geometry(self, area_id: str) -> Geometry | None:
        return self._geometries.get(area_id)

    def feature(self, area_id: str, feature_id: FeatureId) -> FeatureValue | None:
        return self._features.get((area_id, feature_id))

    def tag(self, area_id: str, tag_id: TagId) -> TagValue | None:
        return self._tags.get((area_id, tag_id))

    def cost(self, area_id: str, tenure: Tenure, segment: Segment) -> CostEstimate | None:
        return self._costs.get((area_id, tenure, segment))

    def place(self, place_id: str) -> Place | None:
        return self._places.get(place_id)

    def travel(self, area_id: str, destination_id: str, mode: Mode, basis: PtBasis) -> Travel:
        row = self._rows.get(area_id)
        column = self._columns.get(destination_id)
        if row is None or column is None:
            return MISSING_TRAVEL
        matrix = self.travel_table.matrix(mode, basis)
        # A hand-built release may hold a matrix smaller than its ids say.
        if row >= len(matrix) or column >= len(matrix[row]):
            return MISSING_TRAVEL
        cell = matrix[row][column]
        if cell is None:
            return MISSING_TRAVEL
        if cell == BEYOND_CUTOFF_CELL:
            return BEYOND_CUTOFF_TRAVEL
        return Travel(status=TravelStatus.OK, minutes=cell)

    def stations(self, area_id: str) -> tuple[StationAccess, ...]:
        return self._stations.get(area_id, ())

    def origin(self, part: Part) -> Origin:
        if part is Part.NEIGHBOURHOODS:
            return self.neighbourhoods_origin
        if part is Part.STATIONS:
            return self.stations_origin
        return Origin(source_ids=self.travel_table.source_ids, as_of=self.travel_table.as_of)

    def cutoff(self, mode: Mode) -> int:
        return self.travel_table.cutoff_minutes.of(mode)

    def documents(self) -> dict[str, object]:
        """The content of every file of this release, keyed by file name.

        The inverse of `parse_release`. Writing a release is serialising these,
        so the shape of a file is stated in one module and not two.
        """
        files = _Files(
            manifest=self.manifest,
            neighbourhoods=_NeighbourhoodsFile(
                source_ids=self.neighbourhoods_origin.source_ids,
                as_of=self.neighbourhoods_origin.as_of,
                neighbourhoods=self.neighbourhoods,
            ),
            geometry=_GeometryFile(
                type="FeatureCollection",
                features=tuple(
                    _GeometryFeature(
                        type="Feature",
                        id=g.area_id,
                        properties=_GeometryProperties(area_id=g.area_id),
                        geometry=g.geometry,
                    )
                    for g in self.geometries
                ),
            ),
            catalogue=_CatalogueFile(catalogue_version=CATALOGUE_VERSION, metrics=self.metrics),
            features=_FeaturesFile(rows=self.features),
            tags=_TagsFile(rows=self.tags),
            cost=_CostFile(rows=self.costs),
            destinations=_DestinationsFile(destinations=self.destinations),
            travel=self.travel_table,
            stations=_StationsFile(
                source_ids=self.stations_origin.source_ids,
                as_of=self.stations_origin.as_of,
                rows=self.station_rows,
            ),
            places=_PlacesFile(places=self.places),
        )
        return {name: model.model_dump(mode="json") for name, model in files.by_name().items()}


# The shape of each file. Private: outside this module a release is read through `Release`.


class _NeighbourhoodsFile(Record):
    source_ids: SourceIds
    as_of: str = Field(pattern=DATE_OR_MONTH_PATTERN)
    neighbourhoods: tuple[Neighbourhood, ...]


class _GeometryProperties(Record):
    area_id: AreaId


class _GeometryFeature(Record):
    type: Literal["Feature"]
    id: AreaId
    properties: _GeometryProperties
    geometry: Geometry


class _GeometryFile(Record):
    type: Literal["FeatureCollection"]
    features: tuple[_GeometryFeature, ...]


class _CatalogueFile(Record):
    catalogue_version: int
    metrics: tuple[Metric, ...]


class _FeaturesFile(Record):
    rows: tuple[FeatureValue, ...]


class _TagsFile(Record):
    rows: tuple[TagValue, ...]


class _CostFile(Record):
    rows: tuple[CostEstimate, ...]


class _DestinationsFile(Record):
    destinations: tuple[Destination, ...]


class _StationsFile(Record):
    source_ids: SourceIds
    as_of: str = Field(pattern=DATE_OR_MONTH_PATTERN)
    rows: tuple[StationAccess, ...]


class _PlacesFile(Record):
    places: tuple[Place, ...]


@dataclass(frozen=True)
class _Files:
    """Every file of a release, validated for shape and in the order it was written."""

    manifest: Manifest
    neighbourhoods: _NeighbourhoodsFile
    geometry: _GeometryFile
    catalogue: _CatalogueFile
    features: _FeaturesFile
    tags: _TagsFile
    cost: _CostFile
    destinations: _DestinationsFile
    travel: TravelTable
    stations: _StationsFile
    places: _PlacesFile

    def by_name(self) -> dict[str, Record]:
        return {
            MANIFEST: self.manifest,
            NEIGHBOURHOODS: self.neighbourhoods,
            GEOMETRY: self.geometry,
            CATALOGUE: self.catalogue,
            FEATURES_FILE: self.features,
            TAGS_FILE: self.tags,
            COST: self.cost,
            DESTINATIONS: self.destinations,
            TRAVEL: self.travel,
            STATIONS: self.stations,
            PLACES: self.places,
        }

    def area_ids(self) -> frozenset[str]:
        return frozenset(n.area_id for n in self.neighbourhoods.neighbourhoods)

    def matrices(self) -> tuple[tuple[str, Mode, Matrix], ...]:
        return (
            ("pt_typical", Mode.PT, self.travel.pt_typical),
            ("pt_just_missed", Mode.PT, self.travel.pt_just_missed),
            ("cycle", Mode.CYCLE, self.travel.cycle),
            ("walk", Mode.WALK, self.travel.walk),
        )


_SHAPES: Mapping[str, type[Record]] = {
    MANIFEST: Manifest,
    NEIGHBOURHOODS: _NeighbourhoodsFile,
    GEOMETRY: _GeometryFile,
    CATALOGUE: _CatalogueFile,
    FEATURES_FILE: _FeaturesFile,
    TAGS_FILE: _TagsFile,
    COST: _CostFile,
    DESTINATIONS: _DestinationsFile,
    TRAVEL: TravelTable,
    STATIONS: _StationsFile,
    PLACES: _PlacesFile,
}

# A finding is the file and the row that broke the rule. It never holds a value.
Finding = tuple[str, str]
Rule = Callable[[_Files], Iterable[Finding]]


def versions_match(files: _Files) -> Iterator[Finding]:
    if files.manifest.schema_version != SCHEMA_VERSION:
        yield MANIFEST, "schema_version"
    if files.manifest.catalogue_version != CATALOGUE_VERSION:
        yield MANIFEST, "catalogue_version"
    if files.catalogue.catalogue_version != CATALOGUE_VERSION:
        yield CATALOGUE, "catalogue_version"


def synthetic_is_consistent(files: _Files) -> Iterator[Finding]:
    synthetic = files.manifest.synthetic
    if files.manifest.release_id.startswith(SYNTHETIC_PREFIX) != synthetic:
        yield MANIFEST, "release_id"
    if (files.manifest.city is City.SYN) != synthetic:
        yield MANIFEST, "city"
    ids: tuple[tuple[str, str, Sequence[str]], ...] = (
        (
            NEIGHBOURHOODS,
            "neighbourhoods",
            [n.area_id for n in files.neighbourhoods.neighbourhoods],
        ),
        (DESTINATIONS, "destinations", [d.destination_id for d in files.destinations.destinations]),
        (PLACES, "places", [p.place_id for p in files.places.places]),
        (STATIONS, "rows", [s.station_id for s in files.stations.rows]),
    )
    for file, rows, values in ids:
        for index, value in enumerate(values):
            if value.startswith(SYNTHETIC_PREFIX) != synthetic:
                yield file, f"{rows}[{index}]"
    # The reserved source says "this was made up". A real release may never
    # cite it, and a synthetic one may cite nothing else.
    for index, source in enumerate(files.manifest.sources):
        reserved = source.source_id == SYNTHETIC_SOURCE_ID
        if reserved != synthetic or (reserved and source.attribution != SYNTHETIC_ATTRIBUTION):
            yield MANIFEST, f"sources[{index}]"


def _repeated(keys: Sequence[Hashable]) -> Iterator[int]:
    seen: set[Hashable] = set()
    for index, key in enumerate(keys):
        if key in seen:
            yield index
        seen.add(key)


def _out_of_order(keys: Sequence[str]) -> Iterator[int]:
    """Positions that are not above the one before: a repeat, or a list that is not sorted."""
    for index in range(1, len(keys)):
        if keys[index] <= keys[index - 1]:
            yield index


def ids_are_unique(files: _Files) -> Iterator[Finding]:
    areas = files.neighbourhoods.neighbourhoods
    stations = files.stations.rows
    keyed: tuple[tuple[str, str, Sequence[Hashable]], ...] = (
        (MANIFEST, "sources", [s.source_id for s in files.manifest.sources]),
        (MANIFEST, "files", [f.name for f in files.manifest.files]),
        (NEIGHBOURHOODS, "neighbourhoods", [n.area_id for n in areas]),
        (NEIGHBOURHOODS, "neighbourhoods", [n.slug for n in areas]),
        (GEOMETRY, "features", [g.id for g in files.geometry.features]),
        (CATALOGUE, "metrics", [m.feature_id for m in files.catalogue.metrics]),
        (FEATURES_FILE, "rows", [(r.area_id, r.feature_id) for r in files.features.rows]),
        (TAGS_FILE, "rows", [(r.area_id, r.tag_id) for r in files.tags.rows]),
        (COST, "rows", [(r.area_id, r.tenure, r.segment) for r in files.cost.rows]),
        (DESTINATIONS, "destinations", [d.destination_id for d in files.destinations.destinations]),
        (STATIONS, "rows", [(s.area_id, s.station_id) for s in stations]),
        # At most one station is an area's nearest.
        (
            STATIONS,
            "rows",
            [s.area_id if s.nearest else (s.area_id, i) for i, s in enumerate(stations)],
        ),
        (PLACES, "places", [p.place_id for p in files.places.places]),
    )
    for file, rows, keys in keyed:
        for index in _repeated(keys):
            yield file, f"{rows}[{index}]"

    # An id names one station, whichever area's row it is read from.
    described: dict[str, tuple[str, tuple[str, ...], bool]] = {}
    for index, station in enumerate(stations):
        description = (station.name, station.lines, station.step_free)
        if described.setdefault(station.station_id, description) != description:
            yield STATIONS, f"rows[{index}]"

    # The lists the contract calls sorted. One check covers a repeat and a wrong order.
    ordered: list[tuple[str, str, Sequence[str]]] = [
        (TRAVEL, "area_ids", files.travel.area_ids),
        (TRAVEL, "destination_ids", files.travel.destination_ids),
        (TRAVEL, "source_ids", files.travel.source_ids),
        (NEIGHBOURHOODS, "source_ids", files.neighbourhoods.source_ids),
        (STATIONS, "source_ids", files.stations.source_ids),
    ]
    ordered += [
        (NEIGHBOURHOODS, f"neighbourhoods[{i}].neighbours", n.neighbours)
        for i, n in enumerate(areas)
    ]
    ordered += [
        (CATALOGUE, f"metrics[{i}].source_ids", m.source_ids)
        for i, m in enumerate(files.catalogue.metrics)
    ]
    ordered += [
        (COST, f"rows[{i}].source_ids", r.source_ids) for i, r in enumerate(files.cost.rows)
    ]
    ordered += [(STATIONS, f"rows[{i}].lines", s.lines) for i, s in enumerate(stations)]
    for file, row, keys in ordered:
        for index in _out_of_order(keys):
            yield file, f"{row}[{index}]"


def _cited_sources(files: _Files) -> Iterator[tuple[str, str, str]]:
    for index, source_id in enumerate(files.neighbourhoods.source_ids):
        yield NEIGHBOURHOODS, f"source_ids[{index}]", source_id
    for index, source_id in enumerate(files.stations.source_ids):
        yield STATIONS, f"source_ids[{index}]", source_id
    for index, source_id in enumerate(files.travel.source_ids):
        yield TRAVEL, f"source_ids[{index}]", source_id
    for index, metric in enumerate(files.catalogue.metrics):
        for position, source_id in enumerate(metric.source_ids):
            yield CATALOGUE, f"metrics[{index}].source_ids[{position}]", source_id
    for index, row in enumerate(files.cost.rows):
        for position, source_id in enumerate(row.source_ids):
            yield COST, f"rows[{index}].source_ids[{position}]", source_id
    for index, place in enumerate(files.places.places):
        yield PLACES, f"places[{index}].source_id", place.source_id


def references_resolve(files: _Files) -> Iterator[Finding]:
    areas = files.area_ids()
    destinations = {d.destination_id for d in files.destinations.destinations}
    places = {p.place_id: p for p in files.places.places}
    carried = {m.feature_id for m in files.catalogue.metrics}
    sources = {s.source_id for s in files.manifest.sources}

    for index, area in enumerate(files.neighbourhoods.neighbourhoods):
        for position, neighbour in enumerate(area.neighbours):
            if neighbour not in areas or neighbour == area.area_id:
                yield NEIGHBOURHOODS, f"neighbourhoods[{index}].neighbours[{position}]"
    for index, feature in enumerate(files.geometry.features):
        if feature.id not in areas or feature.properties.area_id != feature.id:
            yield GEOMETRY, f"features[{index}]"
    for index, row in enumerate(files.features.rows):
        if row.area_id not in areas or row.feature_id not in carried:
            yield FEATURES_FILE, f"rows[{index}]"
    in_areas: tuple[tuple[str, Sequence[str]], ...] = (
        (TAGS_FILE, [r.area_id for r in files.tags.rows]),
        (COST, [r.area_id for r in files.cost.rows]),
        (STATIONS, [r.area_id for r in files.stations.rows]),
    )
    for file, area_ids in in_areas:
        for index, area_id in enumerate(area_ids):
            if area_id not in areas:
                yield file, f"rows[{index}]"
    for index, area_id in enumerate(files.travel.area_ids):
        if area_id not in areas:
            yield TRAVEL, f"area_ids[{index}]"
    for index, destination_id in enumerate(files.travel.destination_ids):
        if destination_id not in destinations:
            yield TRAVEL, f"destination_ids[{index}]"
    for index, place in enumerate(files.places.places):
        if place.destination_id not in destinations:
            yield PLACES, f"places[{index}].destination_id"
        coarse = places.get(place.coarse_place_id)
        is_coarse = place.kind in (PlaceKind.STATION, PlaceKind.DISTRICT)
        if (
            coarse is None
            or coarse.kind not in (PlaceKind.STATION, PlaceKind.DISTRICT)
            # A coarse place names itself.
            or (is_coarse and coarse.place_id != place.place_id)
        ):
            yield PLACES, f"places[{index}].coarse_place_id"
    for file, row, source_id in _cited_sources(files):
        if source_id not in sources:
            yield file, row


def catalogue_matches_core(files: _Files) -> Iterator[Finding]:
    for index, metric in enumerate(files.catalogue.metrics):
        core = FEATURES[metric.feature_id]
        stated = (metric.label, metric.dimension, metric.unit, metric.polarity)
        if stated != (core.label, core.dimension, core.unit, core.polarity):
            yield CATALOGUE, f"metrics[{index}]"


def rows_are_complete(files: _Files) -> Iterator[Finding]:
    areas = files.area_ids()
    feature_rows = {(r.area_id, r.feature_id) for r in files.features.rows}
    tag_rows = {(r.area_id, r.tag_id) for r in files.tags.rows}
    drawn = {g.id for g in files.geometry.features}
    for index, area in enumerate(files.neighbourhoods.neighbourhoods):
        # The row that is missing has no position, so the finding names the area's.
        row = f"neighbourhoods[{index}]"
        if any((area.area_id, m.feature_id) not in feature_rows for m in files.catalogue.metrics):
            yield FEATURES_FILE, row
        if any((area.area_id, tag_id) not in tag_rows for tag_id in TagId):
            yield TAGS_FILE, row
        if area.area_id not in drawn:
            yield GEOMETRY, row
    destinations = {d.destination_id for d in files.destinations.destinations}
    if frozenset(files.travel.area_ids) != areas:
        yield TRAVEL, "area_ids"
    if set(files.travel.destination_ids) != destinations:
        yield TRAVEL, "destination_ids"
    for name, _, matrix in files.matrices():
        if len(matrix) != len(files.travel.area_ids):
            yield TRAVEL, name
        for index, cells in enumerate(matrix):
            if len(cells) != len(files.travel.destination_ids):
                yield TRAVEL, f"{name}[{index}]"


def values_are_in_range(files: _Files) -> Iterator[Finding]:
    for index, row in enumerate(files.cost.rows):
        in_order = row.lower_quartile <= row.median <= row.upper_quartile
        if not in_order or row.segment not in segments_for(row.tenure):
            yield COST, f"rows[{index}]"
    for name, mode, matrix in files.matrices():
        cutoff = files.travel.cutoff_minutes.of(mode)
        for index, cells in enumerate(matrix):
            for column, cell in enumerate(cells):
                if cell is not None and cell > cutoff:
                    yield TRAVEL, f"{name}[{index}][{column}]"
    pairs = zip(files.travel.pt_typical, files.travel.pt_just_missed, strict=False)
    for index, (typical_row, missed_row) in enumerate(pairs):
        for column, (typical, missed) in enumerate(zip(typical_row, missed_row, strict=False)):
            # Missing a service can only make a journey longer.
            if typical is not None and missed is not None and 0 <= missed < typical:
                yield TRAVEL, f"pt_just_missed[{index}][{column}]"
    for index, station in enumerate(files.stations.rows):
        if not station.nearest and station.walk_minutes > NEARBY_STATION_MINUTES:
            yield STATIONS, f"rows[{index}].walk_minutes"


def null_means_null(files: _Files) -> Iterator[Finding]:
    for index, row in enumerate(files.features.rows):
        # Below half coverage the source saw too little of the area to give a value.
        if (row.value is None) != (row.percentile is None) or (
            row.value is not None and row.coverage < FEATURE_MIN_COVERAGE
        ):
            yield FEATURES_FILE, f"rows[{index}]"
    for index, row in enumerate(files.tags.rows):
        if (row.raw is None) != (row.score is None) or (
            row.raw is not None and row.coverage < TAG_MIN_COVERAGE_HUNDREDTHS / 100
        ):
            yield TAGS_FILE, f"rows[{index}]"


def sources_are_stated(files: _Files) -> Iterator[Finding]:
    """An empty list or date is caught when the file is read. This is what is left.

    A tag's fact cites the sources of the features in its formula that had a
    value. A tag with a score and no such feature would be a fact with no source.
    """
    valued = {(r.area_id, r.feature_id) for r in files.features.rows if r.value is not None}
    for index, row in enumerate(files.tags.rows):
        if row.score is not None and not any(
            (row.area_id, term.feature_id) in valued for term in TAGS[row.tag_id].terms
        ):
            yield TAGS_FILE, f"rows[{index}]"


def neighbours_are_symmetric(files: _Files) -> Iterator[Finding]:
    neighbours = {n.area_id: set(n.neighbours) for n in files.neighbourhoods.neighbourhoods}
    for index, area in enumerate(files.neighbourhoods.neighbourhoods):
        for position, other in enumerate(area.neighbours):
            if area.area_id not in neighbours.get(other, {area.area_id}):
                yield NEIGHBOURHOODS, f"neighbourhoods[{index}].neighbours[{position}]"


RULES: tuple[Rule, ...] = (
    versions_match,
    synthetic_is_consistent,
    ids_are_unique,
    references_resolve,
    catalogue_matches_core,
    rows_are_complete,
    values_are_in_range,
    null_means_null,
    sources_are_stated,
    neighbours_are_symmetric,
)

_RANGE_ERRORS = frozenset(
    {"greater_than", "greater_than_equal", "less_than", "less_than_equal", "finite_number"}
)
_SOURCE_FIELDS = frozenset({"source_ids", "source_id", "as_of", "vintage"})
_CATALOGUE_FIELDS = frozenset({"feature_id", "tag_id"})


def _row(loc: tuple[int | str, ...]) -> str:
    parts = ""
    for part in loc:
        parts += f"[{part}]" if isinstance(part, int) else f".{part}"
    return parts.lstrip(".")


def _rule_for(loc: tuple[int | str, ...], kind: str) -> str:
    """Which rule of the contract a badly shaped field broke, from where it is and how it failed."""
    names = [part for part in loc if isinstance(part, str)]
    last = names[-1] if names else ""
    if last in _SOURCE_FIELDS:
        return sources_are_stated.__name__
    if last in _CATALOGUE_FIELDS and kind == "enum":
        return catalogue_matches_core.__name__
    if kind in _RANGE_ERRORS:
        return values_are_in_range.__name__
    return "shape_is_valid"


def _shaped(name: str, document: object) -> Record:
    try:
        return _SHAPES[name].model_validate(document)
    except ValidationError as error:
        # Only where and how. The message and the input can repeat a value.
        first = error.errors(include_url=False, include_context=False, include_input=False)[0]
        loc = first["loc"]
        if first["type"] == "extra_forbidden":
            # The name of a field that should not be there is itself something the file said.
            loc = loc[:-1]
        raise ReleaseError(name, _rule_for(loc, first["type"]), _row(loc)) from None


def parse_release(documents: Mapping[str, object]) -> InMemoryRelease:
    """Turn the parsed content of every file, keyed by file name, into a release.

    The only parser. It refuses the release at the first rule that is broken.
    """
    for name in _SHAPES:
        if name not in documents:
            raise ReleaseError(name, "files_are_expected")
    for name in sorted(documents):
        if name not in _SHAPES:
            raise ReleaseError(name, "files_are_expected")

    shaped = {name: _shaped(name, documents[name]) for name in _SHAPES}
    files = _Files(
        manifest=cast(Manifest, shaped[MANIFEST]),
        neighbourhoods=cast(_NeighbourhoodsFile, shaped[NEIGHBOURHOODS]),
        geometry=cast(_GeometryFile, shaped[GEOMETRY]),
        catalogue=cast(_CatalogueFile, shaped[CATALOGUE]),
        features=cast(_FeaturesFile, shaped[FEATURES_FILE]),
        tags=cast(_TagsFile, shaped[TAGS_FILE]),
        cost=cast(_CostFile, shaped[COST]),
        destinations=cast(_DestinationsFile, shaped[DESTINATIONS]),
        travel=cast(TravelTable, shaped[TRAVEL]),
        stations=cast(_StationsFile, shaped[STATIONS]),
        places=cast(_PlacesFile, shaped[PLACES]),
    )
    for rule in RULES:
        for file, row in rule(files):
            raise ReleaseError(file, getattr(rule, "__name__", "rule"), row)

    return InMemoryRelease(
        manifest=files.manifest,
        neighbourhoods=files.neighbourhoods.neighbourhoods,
        neighbourhoods_origin=Origin(
            source_ids=files.neighbourhoods.source_ids, as_of=files.neighbourhoods.as_of
        ),
        travel_table=files.travel,
        stations_origin=Origin(source_ids=files.stations.source_ids, as_of=files.stations.as_of),
        metrics=files.catalogue.metrics,
        features=files.features.rows,
        tags=files.tags.rows,
        costs=files.cost.rows,
        destinations=files.destinations.destinations,
        places=files.places.places,
        station_rows=files.stations.rows,
        geometries=tuple(
            AreaGeometry(area_id=f.id, geometry=f.geometry) for f in files.geometry.features
        ),
    )


def _refuse_constant(_: str) -> Any:
    raise ValueError("NaN and Infinity are not JSON")


def _parsed(name: str, content: bytes) -> object:
    try:
        return json.loads(content.decode("utf-8"), parse_constant=_refuse_constant)
    except ValueError:
        raise ReleaseError(name, "json_is_valid") from None


def open_release(folder_name: str, files: Mapping[str, bytes]) -> InMemoryRelease:
    """Check the bytes of every file in a release folder against its manifest, then parse them.

    It reads no file itself: the caller passes the bytes, keyed by file name.
    A release never changes once written, so a file that does not match the
    checksum the manifest holds for it is refused.
    """
    if MANIFEST not in files:
        raise ReleaseError(MANIFEST, "files_match_manifest")
    manifest_document = _parsed(MANIFEST, files[MANIFEST])
    manifest = cast(Manifest, _shaped(MANIFEST, manifest_document))
    if manifest.release_id != folder_name:
        raise ReleaseError(MANIFEST, "release_id_matches_folder", "release_id")

    listed = {entry.name: entry for entry in manifest.files}
    # An extra file and a missing one are refused alike.
    for name in sorted((set(files) - {MANIFEST}) ^ set(listed)):
        raise ReleaseError(name, "files_match_manifest")
    documents: dict[str, object] = {MANIFEST: manifest_document}
    for name in sorted(listed):
        content = files[name]
        entry = listed[name]
        if len(content) != entry.bytes or hashlib.sha256(content).hexdigest() != entry.sha256:
            raise ReleaseError(name, "files_match_manifest")
        documents[name] = _parsed(name, content)
    return parse_release(documents)
