/**
 * Generated from art/*.sprite.txt by `npm run gen:art`.
 * Never edited by hand: change a drawing and generate again.
 */

/** What the list holds of a drawing. Every length is in art pixels. */
export interface Drawn {
  readonly width: number;
  readonly height: number;
  /** How many drawings of one width stand side by side in a strip. */
  readonly frames?: number;
  /** Where a frame is cut in nine, as `border-image-slice` is written. */
  readonly cut?: readonly [top: number, right: number, foot: number, left: number];
  /** Where a figure is set on the drawing in type. */
  readonly face?: readonly [left: number, top: number, width: number, height: number];
}

/**
 * Every drawing. Its picture is served as `/art/NAME.png`, and is shown at its width and
 * its height times `--px`.
 */
export const ART = {
  "btn-less": { width: 22, height: 22 },
  "btn-less-down": { width: 22, height: 22 },
  "btn-more": { width: 22, height: 22 },
  "btn-more-down": { width: 22, height: 22 },
  "burro-hops": { width: 288, height: 30, frames: 12 },
  "burro-hops-soil": { width: 288, height: 30, frames: 12 },
  "burro-sits": { width: 24, height: 30 },
  "burro-sits-stirs": { width: 360, height: 30, frames: 15 },
  "burro-waits": { width: 24, height: 30 },
  "end-blank": { width: 16, height: 16 },
  "end-built-age-high": { width: 16, height: 16 },
  "end-built-age-low": { width: 16, height: 16 },
  "end-everyday-on-foot-high": { width: 16, height: 16 },
  "end-everyday-on-foot-low": { width: 16, height: 16 },
  "end-family-amenities-high": { width: 16, height: 16 },
  "end-family-amenities-low": { width: 16, height: 16 },
  "end-family-area-high": { width: 16, height: 16 },
  "end-family-area-low": { width: 16, height: 16 },
  "end-foodie-high": { width: 16, height: 16 },
  "end-foodie-low": { width: 16, height: 16 },
  "end-homes-high": { width: 16, height: 16 },
  "end-homes-low": { width: 16, height: 16 },
  "end-leafy-high": { width: 16, height: 16 },
  "end-leafy-low": { width: 16, height: 16 },
  "end-leafy-low-b": { width: 16, height: 16 },
  "end-pace-high": { width: 16, height: 16 },
  "end-pace-low": { width: 16, height: 16 },
  "end-parks-close-by-high": { width: 16, height: 16 },
  "end-parks-close-by-high-b": { width: 16, height: 16 },
  "end-parks-close-by-low": { width: 16, height: 16 },
  "end-parks-close-by-low-b": { width: 16, height: 16 },
  "end-quiet-residential-high": { width: 16, height: 16 },
  "end-quiet-residential-low": { width: 16, height: 16 },
  "end-street-character-high": { width: 16, height: 16 },
  "end-street-character-low": { width: 16, height: 16 },
  "end-village-feel-high": { width: 16, height: 16 },
  "end-village-feel-low": { width: 16, height: 16 },
  "end-well-connected-high": { width: 16, height: 16 },
  "end-well-connected-low": { width: 16, height: 16 },
  "end-works-warehouses-high": { width: 16, height: 16 },
  "end-works-warehouses-low": { width: 16, height: 16 },
  "end-young-professionals-high": { width: 16, height: 16 },
  "end-young-professionals-low": { width: 16, height: 16 },
  "frame-box": { width: 18, height: 18, cut: [4, 6, 6, 4] },
  "frame-box-on": { width: 18, height: 18, cut: [4, 6, 6, 4] },
  "gauge-cell": { width: 6, height: 14 },
  "gauge-cell-full": { width: 6, height: 14 },
  "ground": { width: 192, height: 192 },
  "key-blank": { width: 32, height: 22 },
  "key-buzzy": { width: 32, height: 22 },
  "key-calm": { width: 32, height: 22 },
  "key-flats": { width: 32, height: 22 },
  "key-gritty": { width: 32, height: 22 },
  "key-historic": { width: 32, height: 22 },
  "key-houses": { width: 32, height: 22 },
  "key-least": { width: 32, height: 22 },
  "key-most": { width: 32, height: 22 },
  "key-newer": { width: 32, height: 22 },
  "key-polished": { width: 32, height: 22 },
  "pin": { width: 13, height: 16, face: [2, 2, 9, 7] },
  "thing-alike": { width: 16, height: 16 },
  "thing-alike-off": { width: 16, height: 16 },
  "thing-area": { width: 16, height: 16 },
  "thing-area-off": { width: 16, height: 16 },
  "thing-budget": { width: 16, height: 16 },
  "thing-budget-off": { width: 16, height: 16 },
  "thing-built-age": { width: 16, height: 16 },
  "thing-built-age-off": { width: 16, height: 16 },
  "thing-everyday-on-foot": { width: 16, height: 16 },
  "thing-everyday-on-foot-off": { width: 16, height: 16 },
  "thing-family-air-noise": { width: 16, height: 16 },
  "thing-family-air-noise-off": { width: 16, height: 16 },
  "thing-family-brands": { width: 16, height: 16 },
  "thing-family-brands-off": { width: 16, height: 16 },
  "thing-family-crime": { width: 16, height: 16 },
  "thing-family-crime-off": { width: 16, height: 16 },
  "thing-family-daily-life": { width: 16, height: 16 },
  "thing-family-daily-life-off": { width: 16, height: 16 },
  "thing-family-green": { width: 16, height: 16 },
  "thing-family-green-off": { width: 16, height: 16 },
  "thing-family-pace-food": { width: 16, height: 16 },
  "thing-family-pace-food-off": { width: 16, height: 16 },
  "thing-family-streets-homes": { width: 16, height: 16 },
  "thing-family-streets-homes-off": { width: 16, height: 16 },
  "thing-family-who-lives-there": { width: 16, height: 16 },
  "thing-family-who-lives-there-off": { width: 16, height: 16 },
  "thing-foodie": { width: 16, height: 16 },
  "thing-foodie-off": { width: 16, height: 16 },
  "thing-home": { width: 16, height: 16 },
  "thing-home-off": { width: 16, height: 16 },
  "thing-homes": { width: 16, height: 16 },
  "thing-homes-off": { width: 16, height: 16 },
  "thing-journey": { width: 16, height: 16 },
  "thing-journey-off": { width: 16, height: 16 },
  "thing-leafy": { width: 16, height: 16 },
  "thing-leafy-off": { width: 16, height: 16 },
  "thing-pace": { width: 16, height: 16 },
  "thing-pace-off": { width: 16, height: 16 },
  "thing-parks-close-by": { width: 16, height: 16 },
  "thing-parks-close-by-off": { width: 16, height: 16 },
  "thing-plain": { width: 16, height: 16 },
  "thing-plain-off": { width: 16, height: 16 },
  "thing-quiet-residential": { width: 16, height: 16 },
  "thing-quiet-residential-off": { width: 16, height: 16 },
  "thing-street-character": { width: 16, height: 16 },
  "thing-street-character-off": { width: 16, height: 16 },
  "thing-tenure": { width: 16, height: 16 },
  "thing-tenure-off": { width: 16, height: 16 },
  "thing-usual": { width: 16, height: 16 },
  "thing-usual-off": { width: 16, height: 16 },
  "thing-vibe-family-amenities": { width: 16, height: 16 },
  "thing-vibe-family-amenities-off": { width: 16, height: 16 },
  "thing-vibe-family-area": { width: 16, height: 16 },
  "thing-vibe-family-area-off": { width: 16, height: 16 },
  "thing-village-feel": { width: 16, height: 16 },
  "thing-village-feel-off": { width: 16, height: 16 },
  "thing-well-connected": { width: 16, height: 16 },
  "thing-well-connected-off": { width: 16, height: 16 },
  "thing-works-warehouses": { width: 16, height: 16 },
  "thing-works-warehouses-off": { width: 16, height: 16 },
  "thing-young-professionals": { width: 16, height: 16 },
  "thing-young-professionals-off": { width: 16, height: 16 },
  "tile-grass-a": { width: 16, height: 16 },
  "tile-grass-b": { width: 16, height: 16 },
  "tile-grass-c": { width: 16, height: 16 },
  "tile-grass-d": { width: 16, height: 16 },
  "tile-water-1": { width: 16, height: 16 },
  "tile-water-2": { width: 16, height: 16 },
  "town-lot": { width: 9, height: 5 },
  "town-low": { width: 56, height: 7, frames: 4 },
  "town-mid": { width: 84, height: 11, frames: 6 },
  "town-plot": { width: 56, height: 32 },
  "town-roofs": { width: 70, height: 6, frames: 5 },
  "town-tall": { width: 140, height: 17, frames: 10 },
  "town-trees": { width: 39, height: 11, frames: 3 },
  "ui-approx": { width: 9, height: 6 },
  "ui-arrow": { width: 10, height: 8 },
  "ui-box": { width: 18, height: 18, cut: [4, 6, 6, 4] },
  "ui-box-on": { width: 18, height: 18, cut: [4, 6, 6, 4] },
  "ui-button": { width: 12, height: 10, cut: [3, 3, 4, 3] },
  "ui-button-down": { width: 12, height: 10, cut: [3, 3, 4, 3] },
  "ui-button-go": { width: 12, height: 10, cut: [3, 3, 4, 3] },
  "ui-button-go-down": { width: 12, height: 10, cut: [3, 3, 4, 3] },
  "ui-button-on": { width: 12, height: 10, cut: [3, 3, 4, 3] },
  "ui-button-on-down": { width: 12, height: 10, cut: [3, 3, 4, 3] },
  "ui-button-stop": { width: 12, height: 10, cut: [3, 3, 4, 3] },
  "ui-button-stop-down": { width: 12, height: 10, cut: [3, 3, 4, 3] },
  "ui-carrot": { width: 16, height: 9 },
  "ui-cross": { width: 7, height: 7 },
  "ui-flag": { width: 17, height: 18, face: [3, 2, 12, 10] },
  "ui-key": { width: 16, height: 7 },
  "ui-peg": { width: 7, height: 10 },
  "ui-tradeoff": { width: 16, height: 16 },
  "ui-tradeoff-b": { width: 16, height: 16 },
  "ui-weight": { width: 12, height: 10 },
} as const satisfies Readonly<Record<string, Drawn>>;

/** The name of a drawing. */
export type ArtName = keyof typeof ART;
