"""A small made-up census the tests share, and the one that is committed.

Every name here is made up and every figure is invented. It counts nobody.
"""

import hashlib
import json
from functools import cache
from pathlib import Path
from typing import Any

from burro_core.census import CENSUS, MANIFEST, RESIDENTS_FOLDER, Census, open_census

from .support import RELEASE_ID, area_id

FOLDER = f"{RELEASE_ID}{RESIDENTS_FOLDER}"
AREAS = (area_id(1), area_id(2), area_id(3))
NAME = "Alderwick"
CITY = "Quillhaven"
# A label found in no other file: if it is ever seen outside the census, the census leaked.
CANARY_LABEL = "Made-up group Zq"

SOURCE = {
    "source_id": "synthetic",
    "name": "Synthetic test data",
    "publisher": "Burro",
    "licence": "None. Made up for testing",
    "attribution": "Synthetic data generated by Burro for testing. It describes no real place.",
    "url": "",
    "retrieved_on": "2026-09-23",
}


def row(code: str, label: str, depth: int = 0, heading: str | None = None) -> dict[str, Any]:
    return {"code": code, "heading": heading or label, "label": label, "depth": depth}


def table(code: str, kind: str, unit: str, rows: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "table_code": code,
        "kind": kind,
        "title": f"{kind.replace('_', ' ').capitalize()}, made up",
        "variable": kind.replace("_", " ").capitalize(),
        "universe": "households" if unit == "households" else "usual residents",
        "unit": unit,
        "definition": "Made up for testing. It counts nobody.",
        "source_id": "synthetic",
        "url": "",
        "rows": rows,
    }


TABLES = [
    table(
        "SYN-AGE",
        "age",
        "people",
        [row("age-0", "Aged 0 to 29"), row("age-1", "Aged 30 to 59"), row("age-2", "Aged 60 on")],
    ),
    table(
        "SYN-GRP",
        "ethnic_group",
        "people",
        [
            row("grp-a", "Made-up group A"),
            row("grp-a1", "First part", 1, "Made-up group A: First part"),
            row("grp-a2", "Second part", 1, "Made-up group A: Second part"),
            row("grp-z", CANARY_LABEL),
        ],
    ),
]


def counted(code: str, base: int | None, counts: list[int | None], reason: str | None = None):
    return {"table_code": code, "base": base, "counts": counts, "reason": reason}


def document() -> dict[str, Any]:
    """A census of three areas: one whole, one with a small count, one with too few."""
    return {
        "release_id": RELEASE_ID,
        "synthetic": True,
        "taken_on": "2021-03-21",
        "retrieved_on": "2026-09-23",
        "sources": [dict(SOURCE)],
        "tables": json.loads(json.dumps(TABLES)),
        "whole": {
            "name": CITY,
            "tables": [
                counted("SYN-AGE", 20_000, [8_000, 9_000, 3_000]),
                counted("SYN-GRP", 20_000, [12_000, 7_000, 5_000, 8_000]),
            ],
        },
        "areas": [
            {
                "area_id": AREAS[0],
                "output_areas": 12,
                "tables": [
                    counted("SYN-AGE", 4_040, [1_437, 2_000, 603]),
                    # The last row is under 1 in 100, so no count of it is held.
                    counted("SYN-GRP", 4_040, [4_010, 2_525, 1_485, None]),
                ],
            },
            {
                "area_id": AREAS[1],
                "output_areas": 9,
                "tables": [
                    counted("SYN-AGE", 3_000, [3_000, None, None]),
                    counted("SYN-GRP", 3_000, [2_990, 1_500, 1_490, None]),
                ],
            },
            {
                "area_id": AREAS[2],
                "output_areas": 2,
                "tables": [
                    counted("SYN-AGE", None, [], "too_few"),
                    counted("SYN-GRP", None, [], "not_held"),
                ],
            },
        ],
    }


def as_bytes(found: object) -> bytes:
    text = json.dumps(found, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return (text + "\n").encode("utf-8")


def files(found: dict[str, Any] | None = None) -> dict[str, bytes]:
    """The bytes of the folder of a census, with a manifest that fits them."""
    content = as_bytes(found or document())
    manifest = {
        "release_id": RELEASE_ID,
        "synthetic": True,
        "census_sha256": hashlib.sha256(content).hexdigest(),
        "census_bytes": len(content),
        "sources": [dict(SOURCE)],
    }
    return {MANIFEST: as_bytes(manifest), CENSUS: content}


def opened(found: dict[str, Any] | None = None) -> Census:
    return open_census(FOLDER, files(found), RELEASE_ID, True, AREAS)


COMMITTED = Path(__file__).parents[3] / "data" / "fixtures" / "residents" / FOLDER


@cache
def committed_bytes() -> dict[str, bytes]:
    """The bytes of the made-up census that is committed. Core opens no file: the test does."""
    return {f.name: f.read_bytes() for f in sorted(COMMITTED.iterdir()) if f.name != ".DS_Store"}
