"""Household income on an area's page: what is served of it, and what can never reach it.

Two things are held here. How the figure is shown, so that it reads as the
publisher's estimate and as nothing of Burro's. And that nothing which ranks,
explains, compares or reads a sentence can be handed the figure at all.
"""

import ast
import copy
import hashlib
import json
import re
from collections.abc import Callable
from pathlib import Path
from typing import Any, get_type_hints

import burro_core
import pytest
from burro_core.ids import (
    Describes,
    Dimension,
    FactKind,
    FeatureId,
    Segment,
    Setting,
    TagId,
    TemplateId,
    Tenure,
    UnmetCategory,
)
from burro_core.income import (
    INCOME,
    INCOME_FOLDER,
    MADE_UP,
    MANIFEST,
    NEVER_SAID,
    NO_INCOME,
    ONS,
    RULES,
    Income,
    IncomeError,
    IncomeShown,
    Words,
    day_in_words,
    month_in_words,
    offer,
    open_income,
    parse_income,
    pounds,
    shown,
)
from burro_core.interpret import InterpretRequest, RuleInterpreter
from burro_core.ops import Operations
from burro_core.release import DATA_FILES, InMemoryRelease, Release, ReleaseError, open_release
from burro_core.spec import PreferenceSpec, default_spec

from .support import RELEASE_ID, area_id, fixture_release, small_release

SOURCE = Path(burro_core.__file__).parent
REPOSITORY = Path(__file__).parents[3]
COMMITTED = REPOSITORY / "data" / "fixtures" / "income" / f"{RELEASE_ID}{INCOME_FOLDER}"
FOLDER = f"{RELEASE_ID}{INCOME_FOLDER}"
AREAS = (area_id(1), area_id(2), area_id(3))
Document = dict[str, Any]
Break = Callable[[Document], object]

MADE_UP_SOURCE = {
    "source_id": "synthetic",
    "name": "Synthetic test data",
    "publisher": "Burro",
    "licence": "None. Made up for testing",
    "attribution": "Synthetic data generated by Burro for testing. It describes no real place.",
    "url": "",
    "retrieved_on": "2026-09-23",
}


def document() -> Document:
    """The made-up figures of three areas: two with an estimate, and one with none."""
    return {
        "release_id": RELEASE_ID,
        "synthetic": True,
        "start": "2022-04",
        "end": "2023-03",
        "source": dict(MADE_UP_SOURCE),
        "areas": [
            {"area_id": AREAS[0], "estimate": 52_300, "lower": 46_100, "upper": 59_300},
            {"area_id": AREAS[1], "estimate": 1_234_567, "lower": 1_234_567, "upper": 1_234_567},
            {"area_id": AREAS[2], "estimate": None, "lower": None, "upper": None},
        ],
    }


def as_bytes(held: object) -> bytes:
    return json.dumps(held, sort_keys=True, separators=(",", ":")).encode()


def files(held: Document | None = None) -> dict[str, bytes]:
    content = as_bytes(document() if held is None else held)
    manifest = {
        "release_id": RELEASE_ID,
        "synthetic": True,
        "income_sha256": hashlib.sha256(content).hexdigest(),
        "income_bytes": len(content),
        "source": (document() if held is None else held)["source"],
    }
    return {INCOME: content, MANIFEST: as_bytes(manifest)}


def opened(held: Document | None = None) -> Income:
    return open_income(FOLDER, files(held), RELEASE_ID, True, AREAS)


def of(area: int = 0) -> IncomeShown:
    found = shown(opened(), AREAS[area])
    assert found is not None
    return found


# --- What is shown ----------------------------------------------------------------


def test_the_figure_is_the_publishers_estimate_with_both_its_limits_in_words():
    found = of()
    assert (found.estimate, found.lower, found.upper) == ("£52,300", "£46,100", "£59,300")
    # Both limits are served as they are printed, so that no client joins two figures.
    assert found.limits == "£46,100 to £59,300"
    assert found.none_given is None
    # A figure is said as it is to be printed, so no client works one out or rounds one.
    assert pounds(1_234_567) == "£1,234,567" == of(1).estimate


def test_it_says_the_year_it_is_of_and_that_it_is_from_a_model():
    found = of()
    assert found.year_line == "A made-up year ending March 2023: April 2022 to March 2023."
    assert "model" in found.modelled and "model" in ONS.modelled
    assert ONS.year_line.format(start="April 2022", end="March 2023") == (
        "Financial year ending March 2023: April 2022 to March 2023."
    )
    assert (month_in_words("2023-03"), day_in_words("2026-09-24")) == (
        "March 2023",
        "24 September 2026",
    )


def test_the_real_words_are_the_publishers_own_for_the_kind_the_model_and_the_limits():
    """Each is quoted from the workbook, which a build holds to the same words."""
    assert ONS.kind == "Total annual household income"
    assert '"model-based small area income estimates"' in ONS.modelled
    assert "is the sum of the gross income of every member of the household" in ONS.definition
    assert ONS.limits == "Lower and upper confidence limits"
    assert any("A confidence interval gives an indication" in note for note in ONS.notes)
    assert ONS.source_line.startswith("Source: Office for National Statistics.")
    assert "Open Government Licence v3.0" in ONS.licence_line


def test_it_is_said_to_be_a_mean_of_the_area_and_never_what_a_household_has():
    for words in (ONS, MADE_UP):
        assert "a mean, and not a median" in words.notes[0]
        assert "not what any one household or person here has" in words.notes[0]
        assert any("no change over time" in note or "shows none" in note for note in words.notes)


def test_nothing_else_stands_beside_the_figure():
    """No other area, no figure of the city, no rank, no share and no band."""
    assert set(IncomeShown.model_fields) == {
        "area_id",
        "heading",
        "kind",
        "definition",
        "estimate",
        "limits_label",
        "lower",
        "upper",
        "limits",
        "none_given",
        "year_line",
        "modelled",
        "notes",
        "source_line",
        "licence_line",
        "source_url",
        "open_source",
    }
    served = json.dumps(of().model_dump(mode="json"))
    for other in (AREAS[1], AREAS[2], "1,234,567", "percentile", "rank", "band", "%"):
        assert other not in served, other


def test_an_area_the_publisher_gives_no_estimate_for_says_so_and_holds_no_figure():
    found = of(2)
    assert (found.estimate, found.lower, found.upper, found.limits) == (None, None, None, None)
    assert found.none_given == MADE_UP.none_given
    assert "£" not in json.dumps(found.model_dump(mode="json"))


def test_an_area_the_file_does_not_name_has_nothing_to_show():
    assert shown(opened(), "syn-n9999") is None


def test_the_closed_block_holds_no_figure_and_names_no_area():
    found = offer(opened())
    assert found.available is True
    assert (found.heading, found.intro) == (MADE_UP.heading, MADE_UP.intro)
    assert not re.search(r"[0-9£]", found.heading + found.intro)
    assert "never ranks, filters or compares areas by it" in found.intro
    assert offer(None) == NO_INCOME and NO_INCOME.available is False


@pytest.mark.parametrize("words", [ONS, MADE_UP], ids=["real", "made_up"])
def test_no_word_is_one_burro_would_be_choosing(words: Words):
    """Nothing says that an area has much or little, or stands above or below another."""
    said = " ".join(
        [words.heading, words.intro, words.kind, words.modelled, words.none_given]
        + [note for note in words.notes if not note.startswith("The statistics office says")]
    ).casefold()
    for never in NEVER_SAID:
        assert not re.search(rf"\b{re.escape(never)}\b", said), never


def test_a_made_up_figure_names_no_real_publisher_and_says_it_is_made_up():
    said = json.dumps(MADE_UP.model_dump(mode="json"))
    for real in ("Office for National Statistics", "statistics office", "ONS", "Open Government"):
        assert real not in said, real
    assert "made up" in MADE_UP.heading.casefold() + MADE_UP.kind.casefold()
    assert "made up" in MADE_UP.modelled and "Synthetic" in MADE_UP.licence_line


def test_the_two_sets_of_words_fill_the_same_gaps():
    for name in Words.model_fields:
        real, made_up = getattr(ONS, name), getattr(MADE_UP, name)
        gaps = [set(re.findall(r"{(\w+)}", json.dumps(held))) for held in (real, made_up)]
        assert gaps[0] == gaps[1], name
    assert len(ONS.notes) == len(MADE_UP.notes)


def test_the_committed_figures_are_made_up_and_open_as_the_figures_of_the_release():
    held = {entry.name: entry.read_bytes() for entry in sorted(COMMITTED.iterdir())}
    release = fixture_release()
    found = open_income(
        COMMITTED.name, held, RELEASE_ID, True, [area.area_id for area in release.neighbourhoods]
    )
    assert found.synthetic is True and found.source.source_id == "synthetic"
    assert len(found.areas) == len(release.neighbourhoods)
    assert sum(area.estimate is None for area in found.areas) == 1


# --- What can never reach it --------------------------------------------------------


def _imports(path: Path) -> set[str]:
    found: set[str] = set()
    for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
        if isinstance(node, ast.Import):
            found |= {alias.name for alias in node.names}
        elif isinstance(node, ast.ImportFrom):
            found.add(node.module or "")
            found |= {f"{node.module}.{alias.name}" for alias in node.names}
    return found


def test_nothing_in_core_imports_household_income():
    for path in sorted(SOURCE.glob("*.py")):
        if path.stem == "income":
            continue
        assert not [name for name in _imports(path) if "income" in name], path.name
    assert not [name for name in burro_core.__all__ if "income" in name.casefold()]


def test_household_income_imports_nothing_of_core_that_ranks_or_says():
    ours = {name for name in _imports(SOURCE / "income.py") if name.startswith("burro_core")}
    modules = {name for name in ours if name.count(".") == 1}
    assert modules == {"burro_core._record", "burro_core.ids"}
    # Of the ids it takes the form of an id and nothing of the vocabulary.
    taken = {name.rsplit(".", 1)[1] for name in ours if name.count(".") == 2}
    assert not taken & {"FeatureId", "TagId", "FactKind", "Dimension", "TemplateId", "Segment"}


def test_a_release_cannot_return_household_income():
    members = [name for name in dir(Release) if not name.startswith("_")]
    assert members and not [name for name in members if "income" in name or "earn" in name]
    for name, hint in get_type_hints(InMemoryRelease.__init__).items():
        assert "income" not in name and "income" not in str(hint).casefold(), name
    assert not hasattr(fixture_release(), "income")


def test_a_release_folder_that_holds_a_file_of_income_is_refused():
    assert INCOME not in DATA_FILES
    folder = REPOSITORY / "data" / "fixtures" / "synthetic" / RELEASE_ID
    held = {f.name: f.read_bytes() for f in sorted(folder.iterdir()) if f.name != ".DS_Store"}
    held[INCOME] = files()[INCOME]
    with pytest.raises(ReleaseError) as caught:
        open_release(RELEASE_ID, held)
    assert (caught.value.file, caught.value.rule) == (INCOME, "files_match_manifest")


VOCABULARY = (
    FeatureId,
    TagId,
    FactKind,
    TemplateId,
    Dimension,
    Describes,
    Setting,
    UnmetCategory,
    Segment,
)
NAMES_INCOME = frozenset(
    {"income", "incomes", "earn", "earns", "earnings", "salary", "wage", "pay"}
)


def _parts(value: str) -> set[str]:
    return set(re.split(r"[^a-z0-9]+", value.casefold()))


@pytest.mark.parametrize("vocabulary", VOCABULARY, ids=lambda each: each.__name__)
def test_no_word_of_the_vocabulary_names_income(vocabulary: Any):
    """A spec, an edit, a fact and a sentence are made of these, so none can name it."""
    for member in vocabulary:
        assert not _parts(member.value) & NAMES_INCOME, member


@pytest.mark.parametrize("record", [PreferenceSpec, Operations], ids=lambda each: each.__name__)
def test_no_spec_and_no_edit_has_a_field_for_income(record: Any):
    assert not _parts(json.dumps(record.model_json_schema())) & NAMES_INCOME
    # A field a record does not know is refused, so none can be added by whoever sends one.
    sent = default_spec(Tenure.BUY).model_dump(mode="json") | {"income": {"at_least": 50_000}}
    with pytest.raises(ValueError, match="income"):
        PreferenceSpec.model_validate(sent)


def test_household_income_is_never_handed_a_release():
    """It is told the release's id, whether it is made up, and its areas. It is handed no more."""
    for function in (open_income, parse_income, shown, offer):
        hints = get_type_hints(function)
        assert not [name for name, hint in hints.items() if "Release" in str(hint)], function


@pytest.mark.parametrize(
    "text",
    ["high income", "a high income area", "household income", "well paid", "good salaries"],
)
def test_the_reader_makes_no_edit_and_no_offer_from_a_word_for_income(text: str):
    """No word for what people earn is read as a wish. It weighs nothing, and offers nothing."""
    for tenure in Tenure:
        asked = InterpretRequest(text=text, spec=default_spec(tenure), release=small_release())
        result = RuleInterpreter().interpret(asked)
        assert not result.operations.weight_ops and not result.operations.tag_ops
        assert result.operations.budget_ops == ()
        assert result.suggestions == ()


# --- The one judge of the file ------------------------------------------------------


def test_the_made_up_figures_open():
    found = opened()
    assert [area.area_id for area in found.areas] == list(AREAS)
    assert found.of(AREAS[0]) is not None and found.of("syn-n9999") is None


def refusal(held: dict[str, bytes], folder: str = FOLDER, **given: Any) -> IncomeError:
    with pytest.raises(IncomeError) as caught:
        open_income(
            folder,
            held,
            given.get("release_id", RELEASE_ID),
            given.get("synthetic", True),
            given.get("area_ids", AREAS),
        )
    # A refusal names the file, the row and the rule, and never a value.
    assert not re.search(r"[0-9]{4,}", str(caught.value).replace(RELEASE_ID, ""))
    return caught.value


def broken(change: Break) -> IncomeError:
    held = copy.deepcopy(document())
    change(held)
    return refusal(files(held))


def test_a_folder_that_is_not_named_for_the_release_is_refused():
    assert refusal(files(), folder="syn-2026-09-23-02-income").rule == (
        "folder_is_named_for_the_release"
    )
    assert refusal(files(), folder=f"{RELEASE_ID}-residents").rule == (
        "folder_is_named_for_the_release"
    )


def test_a_file_that_is_missing_extra_or_changed_is_refused():
    assert refusal({MANIFEST: files()[MANIFEST]}).file == INCOME
    assert refusal({INCOME: files()[INCOME]}).file == MANIFEST
    extra = refusal(files() | {"notes.txt": b"x"})
    assert (extra.file, extra.rule) == ("notes.txt", "files_match_manifest")
    changed = files()
    changed[INCOME] = changed[INCOME].replace(b"52300", b"52301")
    assert (refusal(changed).file, refusal(changed).rule) == (INCOME, "files_match_manifest")


def test_figures_made_for_another_release_or_said_to_be_real_are_refused():
    assert refusal(files(), release_id="syn-2026-09-23-02", folder="syn-2026-09-23-02-income").rule
    assert refusal(files(), synthetic=False).rule == "income_is_of_the_release"
    assert broken(lambda held: held.update(release_id="syn-2026-09-23-02")).rule in {
        "income_is_of_the_release",
        "files_match_manifest",
    }


def set_in(*path: str | int, **changes: Any) -> Break:
    """A change that sets fields of what stands at `path` of the document."""

    def change(held: Document) -> None:
        found: Any = held
        for step in path:
            found = found[step]
        found.update(changes)

    return change


def drop_the_last(held: Document) -> None:
    held["areas"].pop()


def turn_round(held: Document) -> None:
    held["areas"].reverse()


def say_twice(held: Document) -> None:
    held["areas"].append(dict(held["areas"][0]))


BROKEN: list[tuple[Break, str]] = [
    (set_in("source", source_id="ons-income-estimates-small-areas"), "made_up_is_said"),
    (set_in("source", url="https://example.org/"), "made_up_is_said"),
    (set_in("areas", 0, area_id="lon-n0001"), "made_up_is_said"),
    (drop_the_last, "areas_are_the_releases"),
    (turn_round, "areas_are_the_releases"),
    (say_twice, "areas_are_the_releases"),
    (set_in("areas", 0, lower=60_000), "limits_hold_the_estimate"),
    (set_in("areas", 0, upper=50_000), "limits_hold_the_estimate"),
    (set_in("areas", 0, lower=None), "limits_hold_the_estimate"),
    (set_in("areas", 2, estimate=40_000), "limits_hold_the_estimate"),
    (set_in(end="2023-04"), "year_is_a_year"),
    (set_in(start="2021-04"), "year_is_a_year"),
    (set_in("areas", 0, estimate=0), "shape_is_valid"),
    (set_in("areas", 0, estimate=52_300.5), "shape_is_valid"),
    (set_in("areas", 0, estimate="52300"), "shape_is_valid"),
    # Nothing can be put beside a figure: a field the record does not know is refused.
    (set_in("areas", 0, percentile=71), "shape_is_valid"),
    (set_in("areas", 0, rank=1), "shape_is_valid"),
    (set_in(city={"estimate": 50_000}), "shape_is_valid"),
    (set_in(end="March 2023"), "shape_is_valid"),
]


@pytest.mark.parametrize(("change", "rule"), BROKEN)
def test_figures_that_break_a_rule_are_refused_and_the_rule_is_named(change: Break, rule: str):
    assert broken(change).rule == rule


def test_a_file_that_is_no_json_is_refused():
    held = files()
    for content in (b"{", b"\xff\xfe", b'{"areas": NaN}'):
        bad = dict(held) | {INCOME: content}
        manifest = json.loads(held[MANIFEST]) | {
            "income_sha256": hashlib.sha256(content).hexdigest(),
            "income_bytes": len(content),
        }
        bad[MANIFEST] = as_bytes(manifest)
        assert refusal(bad).rule == "json_is_valid"


def test_every_rule_is_asked_of_every_file():
    assert [rule.__name__ for rule in RULES] == [
        "income_is_of_the_release",
        "made_up_is_said",
        "areas_are_the_releases",
        "limits_hold_the_estimate",
        "year_is_a_year",
    ]
